// land-data.js — FIFA Wereldreis, fase 3: landinformatie per land
//
// EEN DATASET, GEEN COMPONENT. Zelfde opzet als js/voetbal-data.js: enkel
// gegevens en één opzoekfunctie, geen DOM, geen Leaflet. De renderer staat in
// js/wereldreis.js (landPopup()).
//
// WAAROM HIER EN NIET IN SUPABASE. Identiek voor elke gebruiker, nooit
// geschreven vanuit de app, geen afscherming nodig — dezelfde afweging als
// bij voetbal-data.js. Zie dat bestand voor de volledige redenering.
//
// TAALNIVEAU. Doelgroep is een kind van een jaar of acht: korte zinnen,
// gewone woorden. 'inwoners' is bewust een afgeronde, leesbare tekst
// ("ongeveer 11 miljoen") en geen kaal getal — een exact cijfer verandert
// toch elk jaar en oogt voor een kind niet vriendelijker dan een ronde schatting.
export const LAND = {
  ALG: {
    hoofdstad: "Algiers",
    continent: "Afrika",
    inwoners: "ongeveer 45 miljoen mensen",
    bekendOm: "De Sahara-woestijn en oude Romeinse ruïnes.",
    weetje: "Algerije is het grootste land van Afrika.",
  },
  ARG: {
    hoofdstad: "Buenos Aires",
    continent: "Zuid-Amerika",
    inwoners: "ongeveer 46 miljoen mensen",
    bekendOm: "Tango, gaucho's en de Andes.",
    weetje: "In Argentinië ligt de Aconcagua, de hoogste berg buiten Azië.",
  },
  AUS: {
    hoofdstad: "Canberra",
    continent: "Oceanië",
    inwoners: "ongeveer 26 miljoen mensen",
    bekendOm: "Kangoeroes, koala's en het Great Barrier Reef.",
    weetje: "Australië is zowel een land als een heel continent.",
  },
  AUT: {
    hoofdstad: "Wenen",
    continent: "Europa",
    inwoners: "ongeveer 9 miljoen mensen",
    bekendOm: "De Alpen en beroemde componisten zoals Mozart.",
    weetje: "In Wenen staat een van de oudste pretparken ter wereld, de Prater.",
  },
  BEL: {
    hoofdstad: "Brussel",
    continent: "Europa",
    inwoners: "ruim 11 miljoen mensen",
    bekendOm: "Frieten, chocolade en wafels.",
    weetje: "België heeft drie officiële talen: Nederlands, Frans en Duits.",
  },
  BIH: {
    hoofdstad: "Sarajevo",
    continent: "Europa",
    inwoners: "ongeveer 3 miljoen mensen",
    bekendOm: "De oude bruggen en bergen rond Sarajevo.",
    weetje: "Sarajevo organiseerde ooit de Olympische Winterspelen.",
  },
  BRA: {
    hoofdstad: "Brasília",
    continent: "Zuid-Amerika",
    inwoners: "ongeveer 215 miljoen mensen",
    bekendOm: "Het Amazonewoud, carnaval en voetbal.",
    weetje: "De hoofdstad Brasília werd speciaal gebouwd en heeft de vorm van een vliegtuig.",
  },
  CAN: {
    hoofdstad: "Ottawa",
    continent: "Noord-Amerika",
    inwoners: "ongeveer 39 miljoen mensen",
    bekendOm: "Ahornbladeren, ijshockey en enorme natuurgebieden.",
    weetje: "Canada heeft meer meren dan alle andere landen samen.",
  },
  CIV: {
    hoofdstad: "Yamoussoukro",
    continent: "Afrika",
    inwoners: "ongeveer 29 miljoen mensen",
    bekendOm: "Cacaobonen — het land maakt de meeste chocolade-ingrediënten ter wereld.",
    weetje: "In Yamoussoukro staat een van de grootste kerken ter wereld.",
  },
  COD: {
    hoofdstad: "Kinshasa",
    continent: "Afrika",
    inwoners: "ongeveer 100 miljoen mensen",
    bekendOm: "De rivier de Congo, de op één na langste rivier van Afrika.",
    weetje: "In DR Congo ligt een groot deel van het regenwoud van Afrika.",
  },
  COL: {
    hoofdstad: "Bogotá",
    continent: "Zuid-Amerika",
    inwoners: "ongeveer 52 miljoen mensen",
    bekendOm: "Koffie en kleurrijke bloemen.",
    weetje: "Colombia is een van de landen met de meeste vogelsoorten ter wereld.",
  },
  CPV: {
    hoofdstad: "Praia",
    continent: "Afrika",
    inwoners: "ongeveer 600.000 mensen",
    bekendOm: "Tien vulkanische eilanden in de Atlantische Oceaan.",
    weetje: "Kaapverdië ligt zo'n 600 kilometer uit de kust van West-Afrika.",
  },
  CRO: {
    hoofdstad: "Zagreb",
    continent: "Europa",
    inwoners: "ongeveer 3,8 miljoen mensen",
    bekendOm: "De kustlijn aan de Adriatische Zee met honderden eilandjes.",
    weetje: "De stropdas is oorspronkelijk een Kroatische uitvinding.",
  },
  CUW: {
    hoofdstad: "Willemstad",
    continent: "Noord-Amerika",
    inwoners: "ongeveer 150.000 mensen",
    bekendOm: "Kleurrijke huisjes aan de haven van Willemstad.",
    weetje: "Curaçao ligt in de Caraïbische Zee, vlak bij Venezuela.",
  },
  CZE: {
    hoofdstad: "Praag",
    continent: "Europa",
    inwoners: "ongeveer 10,9 miljoen mensen",
    bekendOm: "Kastelen, de Karelsbrug en het astronomisch uurwerk van Praag.",
    weetje: "Tsjechië heeft geen zee, maar wel duizenden kastelen.",
  },
  ECU: {
    hoofdstad: "Quito",
    continent: "Zuid-Amerika",
    inwoners: "ongeveer 18 miljoen mensen",
    bekendOm: "De Galapagoseilanden, vol bijzondere dieren.",
    weetje: "Ecuador is genoemd naar de evenaar, die er dwars doorheen loopt.",
  },
  EGY: {
    hoofdstad: "Caïro",
    continent: "Afrika",
    inwoners: "ongeveer 105 miljoen mensen",
    bekendOm: "De piramides van Gizeh en de rivier de Nijl.",
    weetje: "De piramides van Gizeh zijn meer dan 4.500 jaar oud.",
  },
  ENG: {
    hoofdstad: "Londen",
    continent: "Europa",
    inwoners: "ongeveer 57 miljoen mensen",
    bekendOm: "Big Ben, dubbeldekkerbussen en de Premier League.",
    weetje: "Voetbal zoals we het nu kennen, is in Engeland ontstaan.",
  },
  ESP: {
    hoofdstad: "Madrid",
    continent: "Europa",
    inwoners: "ongeveer 48 miljoen mensen",
    bekendOm: "Flamenco, tapas en zonnige stranden.",
    weetje: "In Barcelona staat de Sagrada Família, een kerk die al meer dan 140 jaar gebouwd wordt.",
  },
  FRA: {
    hoofdstad: "Parijs",
    continent: "Europa",
    inwoners: "ongeveer 68 miljoen mensen",
    bekendOm: "De Eiffeltoren, croissants en kastelen.",
    weetje: "De Eiffeltoren wordt 's zomers een paar centimeter groter door de warmte.",
  },
  GER: {
    hoofdstad: "Berlijn",
    continent: "Europa",
    inwoners: "ongeveer 84 miljoen mensen",
    bekendOm: "Sprookjesachtige kastelen en de Berlijnse Muur.",
    weetje: "Duitsland heeft meer dan 400 dierentuinen, meer dan enig ander land.",
  },
  GHA: {
    hoofdstad: "Accra",
    continent: "Afrika",
    inwoners: "ongeveer 34 miljoen mensen",
    bekendOm: "Kleurrijke stoffen en cacao.",
    weetje: "Ghana was het eerste Afrikaanse land dat onafhankelijk werd van een kolonisator.",
  },
  HAI: {
    hoofdstad: "Port-au-Prince",
    continent: "Noord-Amerika",
    inwoners: "ongeveer 11,5 miljoen mensen",
    bekendOm: "Levendige kunst en muziek op het Caraïbische eiland Hispaniola.",
    weetje: "Haïti was het eerste land ter wereld opgericht door bevrijde slaven.",
  },
  IRN: {
    hoofdstad: "Teheran",
    continent: "Azië",
    inwoners: "ongeveer 89 miljoen mensen",
    bekendOm: "Duizenden jaren oude paleizen en tapijten.",
    weetje: "In Iran staan enkele van de oudste steden ter wereld.",
  },
  IRQ: {
    hoofdstad: "Bagdad",
    continent: "Azië",
    inwoners: "ongeveer 44 miljoen mensen",
    bekendOm: "Het land tussen de rivieren de Eufraat en de Tigris.",
    weetje: "Dat gebied heet Mesopotamië en wordt de bakermat van de beschaving genoemd.",
  },
  JOR: {
    hoofdstad: "Amman",
    continent: "Azië",
    inwoners: "ongeveer 11 miljoen mensen",
    bekendOm: "De rotsstad Petra, uitgehouwen in roze rotsen.",
    weetje: "Petra is meer dan 2.000 jaar oud en staat op de lijst van wereldwonderen.",
  },
  JPN: {
    hoofdstad: "Tokio",
    continent: "Azië",
    inwoners: "ongeveer 124 miljoen mensen",
    bekendOm: "Sushi, manga en snelle treinen.",
    weetje: "Japan bestaat uit duizenden eilanden.",
  },
  KOR: {
    hoofdstad: "Seoel",
    continent: "Azië",
    inwoners: "ongeveer 52 miljoen mensen",
    bekendOm: "K-pop, technologie en lekker eten zoals bibimbap.",
    weetje: "Zuid-Korea heeft een van de snelste internetverbindingen ter wereld.",
  },
  KSA: {
    hoofdstad: "Riyad",
    continent: "Azië",
    inwoners: "ongeveer 36 miljoen mensen",
    bekendOm: "Enorme zandwoestijnen en de heilige stad Mekka.",
    weetje: "Saoedi-Arabië is bijna zo groot als heel West-Europa samen.",
  },
  MAR: {
    hoofdstad: "Rabat",
    continent: "Afrika",
    inwoners: "ongeveer 37 miljoen mensen",
    bekendOm: "Kleurrijke soeks (markten) en de stad Marrakech.",
    weetje: "In Marokko liggen zowel de Sahara-woestijn als besneeuwde bergtoppen.",
  },
  MEX: {
    hoofdstad: "Mexico-Stad",
    continent: "Noord-Amerika",
    inwoners: "ongeveer 128 miljoen mensen",
    bekendOm: "Piramides van de Maya's en Azteken, en lekker eten zoals taco's.",
    weetje: "Mexico-Stad is gebouwd op de plek van een oud Azteeks eilandmeer.",
  },
  NED: {
    hoofdstad: "Amsterdam",
    continent: "Europa",
    inwoners: "ongeveer 18 miljoen mensen",
    bekendOm: "Molens, tulpen en fietsen.",
    weetje: "Een groot deel van Nederland ligt lager dan de zeespiegel.",
  },
  NOR: {
    hoofdstad: "Oslo",
    continent: "Europa",
    inwoners: "ongeveer 5,5 miljoen mensen",
    bekendOm: "Fjorden — lange, smalle zeearmen tussen hoge bergen.",
    weetje: "In Noorwegen gaat de zon 's zomers boven het noorden soms wekenlang niet onder.",
  },
  NZL: {
    hoofdstad: "Wellington",
    continent: "Oceanië",
    inwoners: "ongeveer 5,2 miljoen mensen",
    bekendOm: "Groene heuvels, schapen en de Maori-cultuur.",
    weetje: "In Nieuw-Zeeland wonen meer schapen dan mensen.",
  },
  PAN: {
    hoofdstad: "Panama-Stad",
    continent: "Noord-Amerika",
    inwoners: "ongeveer 4,4 miljoen mensen",
    bekendOm: "Het Panamakanaal, waar grote schepen tussen twee oceanen varen.",
    weetje: "Panama is het enige land waar je de zon zowel boven de Atlantische als de Grote Oceaan ziet opkomen.",
  },
  PAR: {
    hoofdstad: "Asunción",
    continent: "Zuid-Amerika",
    inwoners: "ongeveer 6,8 miljoen mensen",
    bekendOm: "Reusachtige waterkrachtcentrales en de Guaraní-taal.",
    weetje: "Paraguay heeft geen kustlijn, het land grenst aan geen enkele zee.",
  },
  POR: {
    hoofdstad: "Lissabon",
    continent: "Europa",
    inwoners: "ongeveer 10,3 miljoen mensen",
    bekendOm: "Gekleurde tegels (azulejo's) en heerlijke pasteitjes.",
    weetje: "Portugal is een van de oudste landen van Europa met dezelfde grenzen.",
  },
  QAT: {
    hoofdstad: "Doha",
    continent: "Azië",
    inwoners: "ongeveer 2,7 miljoen mensen",
    bekendOm: "Moderne wolkenkrabbers midden in de woestijn.",
    weetje: "Qatar organiseerde in 2022 het WK voetbal.",
  },
  RSA: {
    hoofdstad: "Pretoria",
    continent: "Afrika",
    inwoners: "ongeveer 60 miljoen mensen",
    bekendOm: "Safari's met leeuwen en olifanten, en Tafelberg in Kaapstad.",
    weetje: "Zuid-Afrika heeft maar liefst drie hoofdsteden: Pretoria, Kaapstad en Bloemfontein.",
  },
  SCO: {
    hoofdstad: "Edinburgh",
    continent: "Europa",
    inwoners: "ongeveer 5,5 miljoen mensen",
    bekendOm: "Kilts, doedelzakken en het meer van Loch Ness.",
    weetje: "Volgens een oude legende leeft er een monster in Loch Ness: Nessie.",
  },
  SEN: {
    hoofdstad: "Dakar",
    continent: "Afrika",
    inwoners: "ongeveer 18 miljoen mensen",
    bekendOm: "Het roze meer (Lac Rose) en levendige muziek.",
    weetje: "Dakar ligt op het meest westelijke puntje van Afrika.",
  },
  SUI: {
    hoofdstad: "Bern",
    continent: "Europa",
    inwoners: "ongeveer 8,8 miljoen mensen",
    bekendOm: "De Alpen, chocolade en horloges.",
    weetje: "Zwitserland heeft vier officiële talen.",
  },
  SWE: {
    hoofdstad: "Stockholm",
    continent: "Europa",
    inwoners: "ongeveer 10,5 miljoen mensen",
    bekendOm: "IKEA, Lego uit de buurlanden en duizenden eilandjes.",
    weetje: "Stockholm is gebouwd over veertien eilanden.",
  },
  TUN: {
    hoofdstad: "Tunis",
    continent: "Afrika",
    inwoners: "ongeveer 12 miljoen mensen",
    bekendOm: "De blauw-witte stad Sidi Bou Said en de Sahara.",
    weetje: "Een deel van de Star Wars-films is opgenomen in de Tunesische woestijn.",
  },
  TUR: {
    hoofdstad: "Ankara",
    continent: "Azië",
    inwoners: "ongeveer 85 miljoen mensen",
    bekendOm: "De stad Istanbul, die op twee continenten tegelijk ligt.",
    weetje: "Een heel klein stukje Turkije ligt in Europa, de rest in Azië.",
  },
  URU: {
    hoofdstad: "Montevideo",
    continent: "Zuid-Amerika",
    inwoners: "ongeveer 3,4 miljoen mensen",
    bekendOm: "Brede stranden en gezellige cafés.",
    weetje: "Uruguay was in 1930 het allereerste gastland van het WK voetbal.",
  },
  USA: {
    hoofdstad: "Washington D.C.",
    continent: "Noord-Amerika",
    inwoners: "ongeveer 335 miljoen mensen",
    bekendOm: "Het Vrijheidsbeeld, de Grand Canyon en Hollywood.",
    weetje: "In 2026 wordt het WK voetbal gespeeld in de VS, Canada en Mexico samen.",
  },
  UZB: {
    hoofdstad: "Tasjkent",
    continent: "Azië",
    inwoners: "ongeveer 35 miljoen mensen",
    bekendOm: "Oude steden langs de Zijderoute, zoals Samarkand.",
    weetje: "Oezbekistan is een van de weinige landen die dubbel landlocked zijn — omringd door landen die zelf ook geen zee hebben.",
  },
};

// De enige toegangsweg tot de gegevens hierboven — zie voetbalVoor() in
// js/voetbal-data.js voor dezelfde redenering.
export function landInfoVoor(landCode) {
  return LAND[landCode] || null;
}
