// voetbal-data.js — FIFA Wereldreis, fase 2: voetbalgegevens per land
//
// EEN DATASET, GEEN COMPONENT. Dit bestand bevat enkel gegevens en één
// opzoekfunctie. Geen DOM, geen Leaflet, geen opmaak — die staan in
// js/wereldreis.js. Zo kan de inhoud aangepast worden zonder aan de kaart te
// raken, en omgekeerd.
//
// WAAROM HIER EN NIET IN SUPABASE. Dit is statische redactionele informatie:
// voor elke gebruiker identiek, nooit geschreven vanuit de app, geen
// afscherming nodig. Een tabel zou een extra migratie, een RLS-policy en een
// netwerkronde bij elke popup kosten, zonder dat er iets tegenover staat. Wil
// je later tóch een tabel — bijvoorbeeld omdat iemand zonder toegang tot de
// code de teksten moet kunnen aanpassen — dan is `voetbalVoor()` onderaan het
// enige wat moet veranderen; de rest van de app kent enkel die functie.
//
// UITBREIDBAAR. Elk land is een object met vaste velden. 'spelers' is bewust
// een lijst en geen enkele naam, zodat er later meer spelers bij kunnen zonder
// het model te breken. Voor fase 3 en later liggen deze velden klaar; de
// renderer in js/wereldreis.js toont ze zodra ze ingevuld zijn en slaat ze
// stil over zolang ze ontbreken:
//
//   trainer:    "Naam van de bondscoach"
//   stadion:    "Naam van het thuisstadion"
//   prestatie:  "Grootste prestatie uit de geschiedenis"
//
// TAALNIVEAU. De doelgroep is een kind van een jaar of acht. Korte zinnen,
// gewone woorden, geen tactisch jargon.

// De FIFA-ranking verandert een paar keer per jaar. Deze cijfers zijn dus een
// momentopname; de popup zet die datum er zichtbaar bij, zodat niemand een
// verouderd getal voor de eeuwige waarheid houdt. Bijwerken doe je hier, op
// één plek.
export const RANKING_STAND = "januari 2026";

// De confederatie is voor een kind een lege afkorting; het werelddeel erachter
// niet. De popup toont ze samen: "UEFA (Europa)".
export const CONFEDERATIES = {
  UEFA: "Europa",
  CONMEBOL: "Zuid-Amerika",
  CAF: "Afrika",
  AFC: "Azië",
  CONCACAF: "Noord- en Midden-Amerika",
  OFC: "Oceanië",
};

// De sleutel is de land_code uit public.sticker_catalogus — dezelfde code die
// op het ruilblad en op de stickers staat (BEL, ARG, GER, ...).
const VOETBAL = {
  ALG: {
    ploeg: "Algerije",
    bijnaam: "De Woestijnvossen",
    shirt: "Wit met groen",
    shirtKleuren: ["#ffffff", "#007a3d"],
    confederatie: "CAF",
    ranking: 36,
    spelers: [{ naam: "Riyad Mahrez", positie: "Aanvaller" }],
    speelstijl: "Snelle spelers met heel veel techniek aan de bal.",
    weetje: "In 2019 won Algerije de Afrika Cup.",
  },
  ARG: {
    ploeg: "Argentinië",
    bijnaam: "La Albiceleste (de wit-blauwen)",
    shirt: "Lichtblauw met wit",
    shirtKleuren: ["#75aadb", "#ffffff"],
    confederatie: "CONMEBOL",
    ranking: 1,
    spelers: [{ naam: "Lionel Messi", positie: "Aanvaller" }],
    speelstijl: "Slim voetbal met korte passjes en veel balbezit.",
    weetje: "Argentinië werd in 2022 wereldkampioen in Qatar.",
  },
  AUS: {
    ploeg: "Australië",
    bijnaam: "De Socceroos",
    shirt: "Geel",
    shirtKleuren: ["#ffcd00"],
    confederatie: "AFC",
    ranking: 24,
    spelers: [{ naam: "Mathew Ryan", positie: "Doelman" }],
    speelstijl: "Hard werken en nooit opgeven, tot de laatste minuut.",
    weetje: "De bijnaam is een woordgrapje: soccer plus kangoeroe wordt Socceroos.",
  },
  AUT: {
    ploeg: "Oostenrijk",
    bijnaam: "Das Team (de ploeg)",
    shirt: "Rood met wit",
    shirtKleuren: ["#ed2939", "#ffffff"],
    confederatie: "UEFA",
    ranking: 25,
    spelers: [{ naam: "David Alaba", positie: "Verdediger" }],
    speelstijl: "Meteen druk zetten, hoog op het veld bij de tegenstander.",
    weetje: "In de jaren dertig heette Oostenrijk het Wunderteam: het wonderteam.",
  },
  BEL: {
    ploeg: "België",
    bijnaam: "De Rode Duivels",
    shirt: "Rood",
    shirtKleuren: ["#e30613"],
    confederatie: "UEFA",
    ranking: 8,
    spelers: [{ naam: "Kevin De Bruyne", positie: "Middenvelder" }],
    speelstijl: "De ploeg speelt graag aanvallend, met lange passes naar voren.",
    weetje: "België stond ooit op nummer 1 van de FIFA-ranking.",
  },
  BIH: {
    ploeg: "Bosnië-Herzegovina",
    bijnaam: "De Draken",
    shirt: "Blauw",
    shirtKleuren: ["#002395"],
    confederatie: "UEFA",
    ranking: 74,
    spelers: [{ naam: "Edin Džeko", positie: "Aanvaller" }],
    speelstijl: "Sterke spitsen die veel doelpunten maken.",
    weetje: "Het land speelde zijn allereerste WK in 2014.",
  },
  BRA: {
    ploeg: "Brazilië",
    bijnaam: "De Seleção",
    shirt: "Geel met blauw",
    shirtKleuren: ["#ffdf00", "#009c3b"],
    confederatie: "CONMEBOL",
    ranking: 5,
    spelers: [{ naam: "Vinícius Júnior", positie: "Aanvaller" }],
    speelstijl: "Vrolijk voetbal met veel dribbels en trucjes.",
    weetje: "Brazilië won het WK al vijf keer, meer dan elk ander land.",
  },
  CAN: {
    ploeg: "Canada",
    bijnaam: "Les Rouges (de roden)",
    shirt: "Rood",
    shirtKleuren: ["#d52b1e"],
    confederatie: "CONCACAF",
    ranking: 30,
    spelers: [{ naam: "Alphonso Davies", positie: "Verdediger" }],
    speelstijl: "Bliksemsnel omschakelen van verdedigen naar aanvallen.",
    weetje: "Canada is in 2026 gastland, samen met Mexico en de Verenigde Staten.",
  },
  CIV: {
    ploeg: "Ivoorkust",
    bijnaam: "De Olifanten",
    shirt: "Oranje",
    shirtKleuren: ["#f77f00"],
    confederatie: "CAF",
    ranking: 40,
    spelers: [{ naam: "Sébastien Haller", positie: "Aanvaller" }],
    speelstijl: "Sterke, atletische spelers die veel duels winnen.",
    weetje: "Ivoorkust won de Afrika Cup van 2023 in eigen land.",
  },
  COD: {
    ploeg: "DR Congo",
    bijnaam: "De Luipaarden",
    shirt: "Blauw",
    shirtKleuren: ["#007fff"],
    confederatie: "CAF",
    ranking: 60,
    spelers: [{ naam: "Cédric Bakambu", positie: "Aanvaller" }],
    speelstijl: "Heel veel loopvermogen en snelle aanvallers.",
    weetje: "In 1974 speelde het land als Zaïre zijn eerste WK.",
  },
  COL: {
    ploeg: "Colombia",
    bijnaam: "Los Cafeteros (de koffieboeren)",
    shirt: "Geel",
    shirtKleuren: ["#fcd116"],
    confederatie: "CONMEBOL",
    ranking: 14,
    spelers: [{ naam: "Luis Díaz", positie: "Aanvaller" }],
    speelstijl: "Technisch voetbal met veel korte passjes.",
    weetje: "De bijnaam komt van de koffie waar Colombia beroemd om is.",
  },
  CPV: {
    ploeg: "Kaapverdië",
    bijnaam: "De Blauwe Haaien",
    shirt: "Blauw",
    shirtKleuren: ["#003893"],
    confederatie: "CAF",
    ranking: 70,
    spelers: [{ naam: "Ryan Mendes", positie: "Aanvaller" }],
    speelstijl: "Een hecht team dat samen verdedigt en samen aanvalt.",
    weetje: "Kaapverdië is een klein eilandenland en speelt zijn allereerste WK.",
  },
  CRO: {
    ploeg: "Kroatië",
    bijnaam: "De Vurigen",
    shirt: "Rood-wit geblokt",
    shirtKleuren: ["#ff0000", "#ffffff"],
    confederatie: "UEFA",
    ranking: 10,
    spelers: [{ naam: "Luka Modrić", positie: "Middenvelder" }],
    speelstijl: "Rustig opbouwen met heel slimme middenvelders.",
    weetje: "Het shirt lijkt op een schaakbord met rode en witte vakjes.",
  },
  CUW: {
    ploeg: "Curaçao",
    bijnaam: "De Blauw-witten",
    shirt: "Blauw",
    shirtKleuren: ["#002b7f"],
    confederatie: "CONCACAF",
    ranking: 85,
    spelers: [{ naam: "Leandro Bacuna", positie: "Middenvelder" }],
    speelstijl: "Dicht bij elkaar verdedigen en dan snel uitbreken.",
    weetje: "Curaçao is het kleinste land dat zich ooit voor een WK plaatste.",
  },
  CZE: {
    ploeg: "Tsjechië",
    bijnaam: "Národní tým (het nationale team)",
    shirt: "Rood",
    shirtKleuren: ["#d7141a"],
    confederatie: "UEFA",
    ranking: 40,
    spelers: [{ naam: "Patrik Schick", positie: "Aanvaller" }],
    speelstijl: "Goed georganiseerd en heel sterk met het hoofd.",
    weetje: "Als Tsjechoslowakije stond het land al twee keer in een WK-finale.",
  },
  ECU: {
    ploeg: "Ecuador",
    bijnaam: "La Tri (de driekleur)",
    shirt: "Geel",
    shirtKleuren: ["#ffd100"],
    confederatie: "CONMEBOL",
    ranking: 25,
    spelers: [{ naam: "Moisés Caicedo", positie: "Middenvelder" }],
    speelstijl: "Sterk en snel, met veel kracht op het middenveld.",
    weetje: "Thuis speelt Ecuador in Quito, bijna drie kilometer boven de zee.",
  },
  EGY: {
    ploeg: "Egypte",
    bijnaam: "De Farao's",
    shirt: "Rood",
    shirtKleuren: ["#c8102e"],
    confederatie: "CAF",
    ranking: 35,
    spelers: [{ naam: "Mohamed Salah", positie: "Aanvaller" }],
    speelstijl: "De bal zo snel mogelijk naar de sterspeler op de flank.",
    weetje: "Egypte won de Afrika Cup al zeven keer, vaker dan elk ander land.",
  },
  ENG: {
    ploeg: "Engeland",
    bijnaam: "The Three Lions (de drie leeuwen)",
    shirt: "Wit",
    shirtKleuren: ["#ffffff"],
    confederatie: "UEFA",
    ranking: 4,
    spelers: [{ naam: "Jude Bellingham", positie: "Middenvelder" }],
    speelstijl: "Snel spel over de vleugels en veel voorzetten.",
    weetje: "Engeland werd in 1966 wereldkampioen in eigen land.",
  },
  ESP: {
    ploeg: "Spanje",
    bijnaam: "La Roja (de rode)",
    shirt: "Rood",
    shirtKleuren: ["#c60b1e"],
    confederatie: "UEFA",
    ranking: 2,
    spelers: [{ naam: "Lamine Yamal", positie: "Aanvaller" }],
    speelstijl: "Heel veel korte passjes, tot er een gaatje valt.",
    weetje: "Spanje won het WK in 2010 en het EK in 2024.",
  },
  FRA: {
    ploeg: "Frankrijk",
    bijnaam: "Les Bleus (de blauwen)",
    shirt: "Blauw",
    shirtKleuren: ["#0055a4"],
    confederatie: "UEFA",
    ranking: 3,
    spelers: [{ naam: "Kylian Mbappé", positie: "Aanvaller" }],
    speelstijl: "Stevig verdedigen en dan razendsnel counteren.",
    weetje: "Frankrijk werd wereldkampioen in 1998 en in 2018.",
  },
  GER: {
    ploeg: "Duitsland",
    bijnaam: "Die Mannschaft (de ploeg)",
    shirt: "Wit met zwart",
    shirtKleuren: ["#ffffff", "#000000"],
    confederatie: "UEFA",
    ranking: 10,
    spelers: [{ naam: "Jamal Musiala", positie: "Middenvelder" }],
    speelstijl: "Goed georganiseerd en altijd gevaarlijk bij een vrije trap.",
    weetje: "Duitsland werd al vier keer wereldkampioen.",
  },
  GHA: {
    ploeg: "Ghana",
    bijnaam: "The Black Stars (de zwarte sterren)",
    shirt: "Wit",
    shirtKleuren: ["#ffffff"],
    confederatie: "CAF",
    ranking: 70,
    spelers: [{ naam: "Mohammed Kudus", positie: "Middenvelder" }],
    speelstijl: "Jonge, snelle spelers die graag dribbelen.",
    weetje: "In 2010 stond Ghana heel dicht bij de halve finale van het WK.",
  },
  HAI: {
    ploeg: "Haïti",
    bijnaam: "Les Grenadiers",
    shirt: "Blauw met rood",
    shirtKleuren: ["#00209f", "#d21034"],
    confederatie: "CONCACAF",
    ranking: 85,
    spelers: [{ naam: "Frantzdy Pierrot", positie: "Aanvaller" }],
    speelstijl: "Vol enthousiasme naar voren spelen.",
    weetje: "In 1974 verraste Haïti de wereld met een doelpunt tegen Italië.",
  },
  IRN: {
    ploeg: "Iran",
    bijnaam: "Team Melli (het nationale team)",
    shirt: "Wit",
    shirtKleuren: ["#ffffff"],
    confederatie: "AFC",
    ranking: 20,
    spelers: [{ naam: "Mehdi Taremi", positie: "Aanvaller" }],
    speelstijl: "Stevig verdedigen met een echte muur van spelers.",
    weetje: "Iran speelde vaker op een WK dan elk ander Aziatisch land.",
  },
  IRQ: {
    ploeg: "Irak",
    bijnaam: "De Leeuwen van Mesopotamië",
    shirt: "Wit met groen",
    shirtKleuren: ["#ffffff", "#007a3d"],
    confederatie: "AFC",
    ranking: 55,
    spelers: [{ naam: "Aymen Hussein", positie: "Aanvaller" }],
    speelstijl: "Fel en strijdlustig: geen bal is verloren.",
    weetje: "In 2007 won Irak verrassend de Azië Cup.",
  },
  JOR: {
    ploeg: "Jordanië",
    bijnaam: "Al-Nashama (de dapperen)",
    shirt: "Wit",
    shirtKleuren: ["#ffffff"],
    confederatie: "AFC",
    ranking: 65,
    spelers: [{ naam: "Mousa Al-Tamari", positie: "Aanvaller" }],
    speelstijl: "Slim wachten en dan snel uitbreken over de vleugels.",
    weetje: "In 2024 haalde Jordanië voor het eerst de finale van de Azië Cup.",
  },
  JPN: {
    ploeg: "Japan",
    bijnaam: "Samurai Blue",
    shirt: "Blauw",
    shirtKleuren: ["#000f8f"],
    confederatie: "AFC",
    ranking: 15,
    spelers: [{ naam: "Kaoru Mitoma", positie: "Aanvaller" }],
    speelstijl: "Snelle combinaties en heel veel loopwerk.",
    weetje: "Japanse supporters ruimen na de wedstrijd hun tribune op.",
  },
  KOR: {
    ploeg: "Zuid-Korea",
    bijnaam: "De Taegeuk-krijgers",
    shirt: "Rood",
    shirtKleuren: ["#cd2e3a"],
    confederatie: "AFC",
    ranking: 22,
    spelers: [{ naam: "Son Heung-min", positie: "Aanvaller" }],
    speelstijl: "Onvermoeibaar druk zetten, de hele wedstrijd lang.",
    weetje: "In 2002 haalde Zuid-Korea in eigen land de halve finale.",
  },
  KSA: {
    ploeg: "Saoedi-Arabië",
    bijnaam: "De Groene Valken",
    shirt: "Wit met groen",
    shirtKleuren: ["#ffffff", "#006c35"],
    confederatie: "AFC",
    ranking: 58,
    spelers: [{ naam: "Salem Al-Dawsari", positie: "Aanvaller" }],
    speelstijl: "Verrassend aanvallend, met de verdediging ver naar voren.",
    weetje: "In 2022 won Saoedi-Arabië van wereldkampioen Argentinië.",
  },
  MAR: {
    ploeg: "Marokko",
    bijnaam: "De Atlasleeuwen",
    shirt: "Rood",
    shirtKleuren: ["#c1272d"],
    confederatie: "CAF",
    ranking: 13,
    spelers: [{ naam: "Achraf Hakimi", positie: "Verdediger" }],
    speelstijl: "Ijzersterk verdedigen en dan pijlsnel counteren.",
    weetje: "In 2022 was Marokko het eerste Afrikaanse land in een WK-halve finale.",
  },
  MEX: {
    ploeg: "Mexico",
    bijnaam: "El Tri (de driekleur)",
    shirt: "Groen",
    shirtKleuren: ["#006847"],
    confederatie: "CONCACAF",
    ranking: 17,
    spelers: [{ naam: "Santiago Giménez", positie: "Aanvaller" }],
    speelstijl: "Veel balbezit en aanvallen over de zijkanten.",
    weetje: "Het Azteca-stadion in Mexico-Stad opende al drie keer een WK.",
  },
  NED: {
    ploeg: "Nederland",
    bijnaam: "Oranje",
    shirt: "Oranje",
    shirtKleuren: ["#f36c21"],
    confederatie: "UEFA",
    ranking: 7,
    spelers: [{ naam: "Virgil van Dijk", positie: "Verdediger" }],
    speelstijl: "Aanvallend voetbal met veel ruimte voor de vleugelspelers.",
    weetje: "Nederland stond al drie keer in een WK-finale, maar won nog nooit.",
  },
  NOR: {
    ploeg: "Noorwegen",
    bijnaam: "De Leeuwen",
    shirt: "Rood",
    shirtKleuren: ["#ba0c2f"],
    confederatie: "UEFA",
    ranking: 30,
    spelers: [{ naam: "Erling Haaland", positie: "Aanvaller" }],
    speelstijl: "Lange ballen naar een heel sterke spits.",
    weetje: "Noorwegen speelt in 2026 zijn eerste WK sinds 1998.",
  },
  NZL: {
    ploeg: "Nieuw-Zeeland",
    bijnaam: "The All Whites",
    shirt: "Wit",
    shirtKleuren: ["#ffffff"],
    confederatie: "OFC",
    ranking: 85,
    spelers: [{ naam: "Chris Wood", positie: "Aanvaller" }],
    speelstijl: "Stevig en fysiek, heel sterk in de lucht.",
    weetje: "Op het WK van 2010 verloor Nieuw-Zeeland geen enkele wedstrijd.",
  },
  PAN: {
    ploeg: "Panama",
    bijnaam: "La Marea Roja (de rode golf)",
    shirt: "Rood",
    shirtKleuren: ["#da121a"],
    confederatie: "CONCACAF",
    ranking: 40,
    spelers: [{ naam: "Adalberto Carrasquilla", positie: "Middenvelder" }],
    speelstijl: "Hard werken en met heel de ploeg samen verdedigen.",
    weetje: "Toen Panama zich in 2017 plaatste voor het WK, werd het een feestdag.",
  },
  PAR: {
    ploeg: "Paraguay",
    bijnaam: "La Albirroja (de rood-witten)",
    shirt: "Rood-wit gestreept",
    shirtKleuren: ["#d52b1e", "#ffffff"],
    confederatie: "CONMEBOL",
    ranking: 50,
    spelers: [{ naam: "Miguel Almirón", positie: "Aanvaller" }],
    speelstijl: "Keihard verdedigen en loeren op die ene kans.",
    weetje: "Doelman José Luis Chilavert scoorde acht keer voor zijn land.",
  },
  POR: {
    ploeg: "Portugal",
    bijnaam: "A Seleção",
    shirt: "Rood met groen",
    shirtKleuren: ["#e42518", "#006600"],
    confederatie: "UEFA",
    ranking: 6,
    spelers: [{ naam: "Cristiano Ronaldo", positie: "Aanvaller" }],
    speelstijl: "Sterke spelers die in hun eentje een wedstrijd kunnen winnen.",
    weetje: "Portugal won het EK van 2016, zijn eerste grote titel ooit.",
  },
  QAT: {
    ploeg: "Qatar",
    bijnaam: "Al-Annabi (de bordeauxrode)",
    shirt: "Bordeauxrood",
    shirtKleuren: ["#8a1538"],
    confederatie: "AFC",
    ranking: 50,
    spelers: [{ naam: "Akram Afif", positie: "Aanvaller" }],
    speelstijl: "Korte passjes en veel beweging zonder bal.",
    weetje: "Qatar was in 2022 zelf het gastland van het WK.",
  },
  RSA: {
    ploeg: "Zuid-Afrika",
    bijnaam: "Bafana Bafana (de jongens)",
    shirt: "Geel",
    shirtKleuren: ["#ffb612"],
    confederatie: "CAF",
    ranking: 60,
    spelers: [{ naam: "Percy Tau", positie: "Aanvaller" }],
    speelstijl: "Vlot combineren over de grond.",
    weetje: "Op het WK van 2010 in Zuid-Afrika klonk overal de vuvuzela.",
  },
  SCO: {
    ploeg: "Schotland",
    bijnaam: "The Scots",
    shirt: "Donkerblauw",
    shirtKleuren: ["#005eb8"],
    confederatie: "UEFA",
    ranking: 45,
    spelers: [{ naam: "Scott McTominay", positie: "Middenvelder" }],
    speelstijl: "Fel duelspel en heel veel strijd.",
    weetje: "Schotland en Engeland speelden in 1872 de allereerste interland ooit.",
  },
  SEN: {
    ploeg: "Senegal",
    bijnaam: "De Leeuwen van Teranga",
    shirt: "Wit met groen",
    shirtKleuren: ["#ffffff", "#00853f"],
    confederatie: "CAF",
    ranking: 18,
    spelers: [{ naam: "Sadio Mané", positie: "Aanvaller" }],
    speelstijl: "Krachtig en snel, met heel sterke aanvallers.",
    weetje: "Senegal won in 2021 voor het eerst de Afrika Cup.",
  },
  SUI: {
    ploeg: "Zwitserland",
    bijnaam: "Nati",
    shirt: "Rood",
    shirtKleuren: ["#d52b1e"],
    confederatie: "UEFA",
    ranking: 19,
    spelers: [{ naam: "Granit Xhaka", positie: "Middenvelder" }],
    speelstijl: "Heel gedisciplineerd: iedereen kent precies zijn taak.",
    weetje: "Zwitserland haalt bijna elk groot toernooi de tweede ronde.",
  },
  SWE: {
    ploeg: "Zweden",
    bijnaam: "Blågult (blauwgeel)",
    shirt: "Geel met blauw",
    shirtKleuren: ["#fecc00", "#006aa7"],
    confederatie: "UEFA",
    ranking: 35,
    spelers: [{ naam: "Alexander Isak", positie: "Aanvaller" }],
    speelstijl: "Rustig opbouwen en toeslaan bij de omschakeling.",
    weetje: "In 1958 speelde Zweden de WK-finale in eigen land.",
  },
  TUN: {
    ploeg: "Tunesië",
    bijnaam: "De Adelaars van Carthago",
    shirt: "Rood",
    shirtKleuren: ["#e70013"],
    confederatie: "CAF",
    ranking: 45,
    spelers: [{ naam: "Hannibal Mejbri", positie: "Middenvelder" }],
    speelstijl: "Dicht bij elkaar spelen en loeren op de counter.",
    weetje: "In 1978 won Tunesië als eerste Afrikaanse land een WK-wedstrijd.",
  },
  TUR: {
    ploeg: "Turkije",
    bijnaam: "De Maansterren",
    shirt: "Rood",
    shirtKleuren: ["#e30a17"],
    confederatie: "UEFA",
    ranking: 28,
    spelers: [{ naam: "Arda Güler", positie: "Middenvelder" }],
    speelstijl: "Vurig en aanvallend, met heel veel passie.",
    weetje: "Op het WK van 2002 werd Turkije verrassend derde.",
  },
  URU: {
    ploeg: "Uruguay",
    bijnaam: "La Celeste (de hemelsblauwe)",
    shirt: "Lichtblauw",
    shirtKleuren: ["#5cbfeb"],
    confederatie: "CONMEBOL",
    ranking: 15,
    spelers: [{ naam: "Federico Valverde", positie: "Middenvelder" }],
    speelstijl: "Nooit opgeven en elk duel willen winnen.",
    weetje: "Uruguay won in 1930 het allereerste WK ooit.",
  },
  USA: {
    ploeg: "Verenigde Staten",
    bijnaam: "The Stars and Stripes",
    shirt: "Wit",
    shirtKleuren: ["#ffffff"],
    confederatie: "CONCACAF",
    ranking: 16,
    spelers: [{ naam: "Christian Pulisic", positie: "Aanvaller" }],
    speelstijl: "Atletisch voetbal met heel veel tempo.",
    weetje: "In 2026 wordt er in elf Amerikaanse steden WK-voetbal gespeeld.",
  },
  UZB: {
    ploeg: "Oezbekistan",
    bijnaam: "De Witte Wolven",
    shirt: "Wit",
    shirtKleuren: ["#ffffff"],
    confederatie: "AFC",
    ranking: 55,
    spelers: [{ naam: "Eldor Shomurodov", positie: "Aanvaller" }],
    speelstijl: "Geduldig opbouwen met veel balbezit.",
    weetje: "Oezbekistan speelt in 2026 zijn allereerste WK.",
  },
};

// De enige toegangsweg tot de gegevens hierboven. Wordt dit later een tabel in
// Supabase, dan verandert enkel deze functie (en wordt ze async) — de kaart en
// de popup blijven ongewijzigd.
export function voetbalVoor(landCode) {
  return VOETBAL[landCode] || null;
}

// Voor het volledige werelddeel achter een confederatiecode. Onbekende code:
// gewoon de code teruggeven, dat is nog altijd beter dan een lege regel.
export function confederatieNaam(code) {
  return CONFEDERATIES[code] ? `${code} (${CONFEDERATIES[code]})` : code;
}
