-- Panini Ruilportaal — Seed: referentielijst van alle stickers
-- Voer dit uit na sql/003_ruillijst.sql. Veilig opnieuw uit te voeren:
-- bestaande codes worden overgeslagen (on conflict do nothing).
--
-- Bron: laststicker.com-checklist, via de publieke dataset
-- github.com/danieltartaro/sticker-swap (MIT), omgezet naar Nederlandse
-- landnamen. 1034 stickers, waarvan 54 glansvarianten
-- (Europese editie: Duitsland, België, Frankrijk).

insert into public.sticker_catalogus
  (categorie, land_code, land_naam, nummer, code, naam, glans)
values
  ('logo', 'PANINI', 'Panini-logo', 0, '00', 'Panini Logo', false),
  ('special', 'FWC', 'WK-specials', 1, 'FWC1', 'Official Emblem1', false),
  ('special', 'FWC', 'WK-specials', 2, 'FWC2', 'Official Emblem2', false),
  ('special', 'FWC', 'WK-specials', 3, 'FWC3', 'Official Mascots', false),
  ('special', 'FWC', 'WK-specials', 4, 'FWC4', 'Official Slogan', false),
  ('special', 'FWC', 'WK-specials', 5, 'FWC5', 'Official Ball', false),
  ('special', 'FWC', 'WK-specials', 6, 'FWC6', 'Canada', false),
  ('special', 'FWC', 'WK-specials', 7, 'FWC7', 'Mexico', false),
  ('special', 'FWC', 'WK-specials', 8, 'FWC8', 'USA', false),
  ('team', 'MEX', 'Mexico', 1, 'MEX1', 'Emblem', false),
  ('team', 'MEX', 'Mexico', 2, 'MEX2', 'Luis Malagón', false),
  ('team', 'MEX', 'Mexico', 3, 'MEX3', 'Johan Vasquez', false),
  ('team', 'MEX', 'Mexico', 4, 'MEX4', 'Jorge Sánchez', false),
  ('team', 'MEX', 'Mexico', 5, 'MEX5', 'Cesar Montes', false),
  ('team', 'MEX', 'Mexico', 6, 'MEX6', 'Jesus Gallardo', false),
  ('team', 'MEX', 'Mexico', 7, 'MEX7', 'Israel Reyes', false),
  ('team', 'MEX', 'Mexico', 8, 'MEX8', 'Diego Lainez', false),
  ('team', 'MEX', 'Mexico', 9, 'MEX9', 'Carlos Rodriguez', false),
  ('team', 'MEX', 'Mexico', 10, 'MEX10', 'Edson Alvarez', false),
  ('team', 'MEX', 'Mexico', 11, 'MEX11', 'Orbelin Pineda', false),
  ('team', 'MEX', 'Mexico', 12, 'MEX12', 'Marcel Ruiz', false),
  ('team', 'MEX', 'Mexico', 13, 'MEX13', 'Team Photo', false),
  ('team', 'MEX', 'Mexico', 14, 'MEX14', 'Érick Sánchez', false),
  ('team', 'MEX', 'Mexico', 15, 'MEX15', 'Hirving Lozano', false),
  ('team', 'MEX', 'Mexico', 16, 'MEX16', 'Santiago Giménez', false),
  ('team', 'MEX', 'Mexico', 17, 'MEX17', 'Raúl Jiménez', false),
  ('team', 'MEX', 'Mexico', 18, 'MEX18', 'Alexis Vega', false),
  ('team', 'MEX', 'Mexico', 19, 'MEX19', 'Roberto Alvarado', false),
  ('team', 'MEX', 'Mexico', 20, 'MEX20', 'Cesar Huerta', false),
  ('team', 'RSA', 'Zuid-Afrika', 1, 'RSA1', 'Emblem', false),
  ('team', 'RSA', 'Zuid-Afrika', 2, 'RSA2', 'Ronwen Williams', false),
  ('team', 'RSA', 'Zuid-Afrika', 3, 'RSA3', 'Sipho Chaine', false),
  ('team', 'RSA', 'Zuid-Afrika', 4, 'RSA4', 'Aubrey Modiba', false),
  ('team', 'RSA', 'Zuid-Afrika', 5, 'RSA5', 'Samukele Kabini', false),
  ('team', 'RSA', 'Zuid-Afrika', 6, 'RSA6', 'Mbekezeli Mbokazi', false),
  ('team', 'RSA', 'Zuid-Afrika', 7, 'RSA7', 'Khulumani Ndamane', false),
  ('team', 'RSA', 'Zuid-Afrika', 8, 'RSA8', 'Siyabonga Ngezana', false),
  ('team', 'RSA', 'Zuid-Afrika', 9, 'RSA9', 'Khuliso Mudau', false),
  ('team', 'RSA', 'Zuid-Afrika', 10, 'RSA10', 'Nkosinathi Sibisi', false),
  ('team', 'RSA', 'Zuid-Afrika', 11, 'RSA11', 'Teboho Mokoena', false),
  ('team', 'RSA', 'Zuid-Afrika', 12, 'RSA12', 'Thalente Mbatha', false),
  ('team', 'RSA', 'Zuid-Afrika', 13, 'RSA13', 'Team Photo', false),
  ('team', 'RSA', 'Zuid-Afrika', 14, 'RSA14', 'Bathusi Aubaas', false),
  ('team', 'RSA', 'Zuid-Afrika', 15, 'RSA15', 'Yaya Sithole', false),
  ('team', 'RSA', 'Zuid-Afrika', 16, 'RSA16', 'Sipho Mbule', false),
  ('team', 'RSA', 'Zuid-Afrika', 17, 'RSA17', 'Lyle Foster', false),
  ('team', 'RSA', 'Zuid-Afrika', 18, 'RSA18', 'Iqraam Rayners', false),
  ('team', 'RSA', 'Zuid-Afrika', 19, 'RSA19', 'Mohau Nkota', false),
  ('team', 'RSA', 'Zuid-Afrika', 20, 'RSA20', 'Oswin Appollis', false),
  ('team', 'KOR', 'Zuid-Korea', 1, 'KOR1', 'Emblem', false),
  ('team', 'KOR', 'Zuid-Korea', 2, 'KOR2', 'Hyeon-woo Jo', false),
  ('team', 'KOR', 'Zuid-Korea', 3, 'KOR3', 'Seung-Gyu Kim', false),
  ('team', 'KOR', 'Zuid-Korea', 4, 'KOR4', 'Min-jae Kim', false),
  ('team', 'KOR', 'Zuid-Korea', 5, 'KOR5', 'Yu-min Cho', false),
  ('team', 'KOR', 'Zuid-Korea', 6, 'KOR6', 'Young-woo Seol', false),
  ('team', 'KOR', 'Zuid-Korea', 7, 'KOR7', 'Han-beom Lee', false),
  ('team', 'KOR', 'Zuid-Korea', 8, 'KOR8', 'Tae-seok Lee', false),
  ('team', 'KOR', 'Zuid-Korea', 9, 'KOR9', 'Myung-jae Lee', false),
  ('team', 'KOR', 'Zuid-Korea', 10, 'KOR10', 'Jae-sung Lee', false),
  ('team', 'KOR', 'Zuid-Korea', 11, 'KOR11', 'In-beom Hwang', false),
  ('team', 'KOR', 'Zuid-Korea', 12, 'KOR12', 'Kang-in Lee', false),
  ('team', 'KOR', 'Zuid-Korea', 13, 'KOR13', 'Team Photo', false),
  ('team', 'KOR', 'Zuid-Korea', 14, 'KOR14', 'Seung-ho Paik', false),
  ('team', 'KOR', 'Zuid-Korea', 15, 'KOR15', 'Jens Castrop', false),
  ('team', 'KOR', 'Zuid-Korea', 16, 'KOR16', 'Dongg-yeong Lee', false),
  ('team', 'KOR', 'Zuid-Korea', 17, 'KOR17', 'Gue-sung Cho', false),
  ('team', 'KOR', 'Zuid-Korea', 18, 'KOR18', 'Heung-min Son', false),
  ('team', 'KOR', 'Zuid-Korea', 19, 'KOR19', 'Hee-chan Hwang', false),
  ('team', 'KOR', 'Zuid-Korea', 20, 'KOR20', 'Hyeon-Gyu Oh', false),
  ('team', 'CZE', 'Tsjechië', 1, 'CZE1', 'Emblem', false),
  ('team', 'CZE', 'Tsjechië', 2, 'CZE2', 'Matej Kovar', false),
  ('team', 'CZE', 'Tsjechië', 3, 'CZE3', 'Jindrich Stanek', false),
  ('team', 'CZE', 'Tsjechië', 4, 'CZE4', 'Ladislav Krejci', false),
  ('team', 'CZE', 'Tsjechië', 5, 'CZE5', 'Vladimir Coufal', false),
  ('team', 'CZE', 'Tsjechië', 6, 'CZE6', 'Jaroslav Zeleny', false),
  ('team', 'CZE', 'Tsjechië', 7, 'CZE7', 'Tomas Holes', false),
  ('team', 'CZE', 'Tsjechië', 8, 'CZE8', 'David Zima', false),
  ('team', 'CZE', 'Tsjechië', 9, 'CZE9', 'Michal Sadilek', false),
  ('team', 'CZE', 'Tsjechië', 10, 'CZE10', 'Lukas Provod', false),
  ('team', 'CZE', 'Tsjechië', 11, 'CZE11', 'Lukas Cerv', false),
  ('team', 'CZE', 'Tsjechië', 12, 'CZE12', 'Tomas Soucek', false),
  ('team', 'CZE', 'Tsjechië', 13, 'CZE13', 'Team Photo', false),
  ('team', 'CZE', 'Tsjechië', 14, 'CZE14', 'Pavel Sulc', false),
  ('team', 'CZE', 'Tsjechië', 15, 'CZE15', 'Matej Vydra', false),
  ('team', 'CZE', 'Tsjechië', 16, 'CZE16', 'Vasil Kusej', false),
  ('team', 'CZE', 'Tsjechië', 17, 'CZE17', 'Tomas Chory', false),
  ('team', 'CZE', 'Tsjechië', 18, 'CZE18', 'Vaclav Cerny', false),
  ('team', 'CZE', 'Tsjechië', 19, 'CZE19', 'Adam Hlozek', false),
  ('team', 'CZE', 'Tsjechië', 20, 'CZE20', 'Patrik Schick', false),
  ('team', 'CAN', 'Canada', 1, 'CAN1', 'Emblem', false),
  ('team', 'CAN', 'Canada', 2, 'CAN2', 'Dayne St.Clair', false),
  ('team', 'CAN', 'Canada', 3, 'CAN3', 'Alphonso Davies', false),
  ('team', 'CAN', 'Canada', 4, 'CAN4', 'Alistair Johnston', false),
  ('team', 'CAN', 'Canada', 5, 'CAN5', 'Samuel Adekugbe', false),
  ('team', 'CAN', 'Canada', 6, 'CAN6', 'Richie Laryea', false),
  ('team', 'CAN', 'Canada', 7, 'CAN7', 'Derek Cornelius', false),
  ('team', 'CAN', 'Canada', 8, 'CAN8', 'Moïse Bombito', false),
  ('team', 'CAN', 'Canada', 9, 'CAN9', 'Kamal Miller', false),
  ('team', 'CAN', 'Canada', 10, 'CAN10', 'Stephen Eustáquio', false),
  ('team', 'CAN', 'Canada', 11, 'CAN11', 'Ismaël Koné', false),
  ('team', 'CAN', 'Canada', 12, 'CAN12', 'Jonathan Osorio', false),
  ('team', 'CAN', 'Canada', 13, 'CAN13', 'Team Photo', false),
  ('team', 'CAN', 'Canada', 14, 'CAN14', 'Jacob Shaffelburg', false),
  ('team', 'CAN', 'Canada', 15, 'CAN15', 'Mathieu Choinière', false),
  ('team', 'CAN', 'Canada', 16, 'CAN16', 'Niko Sigur', false),
  ('team', 'CAN', 'Canada', 17, 'CAN17', 'Tajon Buchanan', false),
  ('team', 'CAN', 'Canada', 18, 'CAN18', 'Liam Millar', false),
  ('team', 'CAN', 'Canada', 19, 'CAN19', 'Cyle Larin', false),
  ('team', 'CAN', 'Canada', 20, 'CAN20', 'Jonathan David', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 1, 'BIH1', 'Emblem', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 2, 'BIH2', 'Nikola Vasilj', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 3, 'BIH3', 'Amer Dedic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 4, 'BIH4', 'Sead Kolasinac', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 5, 'BIH5', 'Tarik Muharemovic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 6, 'BIH6', 'Nihad Mujakic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 7, 'BIH7', 'Nikola Katic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 8, 'BIH8', 'Amir Hadziahmetovic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 9, 'BIH9', 'Benjamin Tahirovic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 10, 'BIH10', 'Armin Gigovic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 11, 'BIH11', 'Ivan Sunjic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 12, 'BIH12', 'Ivan Basic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 13, 'BIH13', 'Team Photo', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 14, 'BIH14', 'Dzenis Burnic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 15, 'BIH15', 'Esmir Bajraktarevic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 16, 'BIH16', 'Amar Memic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 17, 'BIH17', 'Ermedin Demirovic', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 18, 'BIH18', 'Edin Dzeko', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 19, 'BIH19', 'Samed Bazdar', false),
  ('team', 'BIH', 'Bosnië-Herzegovina', 20, 'BIH20', 'Haris Tabakovic', false),
  ('team', 'QAT', 'Qatar', 1, 'QAT1', 'Emblem', false),
  ('team', 'QAT', 'Qatar', 2, 'QAT2', 'Meshaal Barsham', false),
  ('team', 'QAT', 'Qatar', 3, 'QAT3', 'Sultan Albrake', false),
  ('team', 'QAT', 'Qatar', 4, 'QAT4', 'Lucas Mendes', false),
  ('team', 'QAT', 'Qatar', 5, 'QAT5', 'Homam Ahmed', false),
  ('team', 'QAT', 'Qatar', 6, 'QAT6', 'Boualem Khoukhi', false),
  ('team', 'QAT', 'Qatar', 7, 'QAT7', 'Pedro Miguel', false),
  ('team', 'QAT', 'Qatar', 8, 'QAT8', 'Tarek Salman', false),
  ('team', 'QAT', 'Qatar', 9, 'QAT9', 'Mohamed Al-Mannai', false),
  ('team', 'QAT', 'Qatar', 10, 'QAT10', 'Karim Boudiaf', false),
  ('team', 'QAT', 'Qatar', 11, 'QAT11', 'Assim Madibo', false),
  ('team', 'QAT', 'Qatar', 12, 'QAT12', 'Ahmed Fatehi', false),
  ('team', 'QAT', 'Qatar', 13, 'QAT13', 'Team Photo', false),
  ('team', 'QAT', 'Qatar', 14, 'QAT14', 'Mohammed Waad', false),
  ('team', 'QAT', 'Qatar', 15, 'QAT15', 'Abdulaziz Hatem', false),
  ('team', 'QAT', 'Qatar', 16, 'QAT16', 'Hassan Al-Haydos', false),
  ('team', 'QAT', 'Qatar', 17, 'QAT17', 'Edmilson Junior', false),
  ('team', 'QAT', 'Qatar', 18, 'QAT18', 'Akram Hassan Afif', false),
  ('team', 'QAT', 'Qatar', 19, 'QAT19', 'Ahmed Al Ganehi', false),
  ('team', 'QAT', 'Qatar', 20, 'QAT20', 'Almoez Ali', false),
  ('team', 'SUI', 'Zwitserland', 1, 'SUI1', 'Emblem', false),
  ('team', 'SUI', 'Zwitserland', 2, 'SUI2', 'Gregor Kobel', false),
  ('team', 'SUI', 'Zwitserland', 3, 'SUI3', 'Yvon Mvogo', false),
  ('team', 'SUI', 'Zwitserland', 4, 'SUI4', 'Manuel Akanji', false),
  ('team', 'SUI', 'Zwitserland', 5, 'SUI5', 'Ricardo Rodriguez', false),
  ('team', 'SUI', 'Zwitserland', 6, 'SUI6', 'Nico Elvedi', false),
  ('team', 'SUI', 'Zwitserland', 7, 'SUI7', 'Aurèle Amenda', false),
  ('team', 'SUI', 'Zwitserland', 8, 'SUI8', 'Silvan Widmer', false),
  ('team', 'SUI', 'Zwitserland', 9, 'SUI9', 'Granit Xhaka', false),
  ('team', 'SUI', 'Zwitserland', 10, 'SUI10', 'Denis Zakaria', false),
  ('team', 'SUI', 'Zwitserland', 11, 'SUI11', 'Remo Freuler', false),
  ('team', 'SUI', 'Zwitserland', 12, 'SUI12', 'Fabian Rieder', false),
  ('team', 'SUI', 'Zwitserland', 13, 'SUI13', 'Team Photo', false),
  ('team', 'SUI', 'Zwitserland', 14, 'SUI14', 'Ardon Jashari', false),
  ('team', 'SUI', 'Zwitserland', 15, 'SUI15', 'Johan Manzambi', false),
  ('team', 'SUI', 'Zwitserland', 16, 'SUI16', 'Michel Aebischer', false),
  ('team', 'SUI', 'Zwitserland', 17, 'SUI17', 'Breel Embolo', false),
  ('team', 'SUI', 'Zwitserland', 18, 'SUI18', 'Ruben Vargas', false),
  ('team', 'SUI', 'Zwitserland', 19, 'SUI19', 'Dan Ndoye', false),
  ('team', 'SUI', 'Zwitserland', 20, 'SUI20', 'Zeki Amdouni', false),
  ('team', 'BRA', 'Brazilië', 1, 'BRA1', 'Emblem', false),
  ('team', 'BRA', 'Brazilië', 2, 'BRA2', 'Alisson', false),
  ('team', 'BRA', 'Brazilië', 3, 'BRA3', 'Bento', false),
  ('team', 'BRA', 'Brazilië', 4, 'BRA4', 'Marquinhos', false),
  ('team', 'BRA', 'Brazilië', 5, 'BRA5', 'Éder Militão', false),
  ('team', 'BRA', 'Brazilië', 6, 'BRA6', 'Gabriel Magalhães', false),
  ('team', 'BRA', 'Brazilië', 7, 'BRA7', 'Danilo', false),
  ('team', 'BRA', 'Brazilië', 8, 'BRA8', 'Wesley', false),
  ('team', 'BRA', 'Brazilië', 9, 'BRA9', 'Lucas Paquetá', false),
  ('team', 'BRA', 'Brazilië', 10, 'BRA10', 'Casemiro', false),
  ('team', 'BRA', 'Brazilië', 11, 'BRA11', 'Bruno Guimarães', false),
  ('team', 'BRA', 'Brazilië', 12, 'BRA12', 'Luiz Henrique', false),
  ('team', 'BRA', 'Brazilië', 13, 'BRA13', 'Team Photo', false),
  ('team', 'BRA', 'Brazilië', 14, 'BRA14', 'Vinicius Júnior', false),
  ('team', 'BRA', 'Brazilië', 15, 'BRA15', 'Rodrygo', false),
  ('team', 'BRA', 'Brazilië', 16, 'BRA16', 'João Pedro', false),
  ('team', 'BRA', 'Brazilië', 17, 'BRA17', 'Matheus Cunha', false),
  ('team', 'BRA', 'Brazilië', 18, 'BRA18', 'Gabriel Martinelli', false),
  ('team', 'BRA', 'Brazilië', 19, 'BRA19', 'Raphinha', false),
  ('team', 'BRA', 'Brazilië', 20, 'BRA20', 'Estévão', false),
  ('team', 'MAR', 'Marokko', 1, 'MAR1', 'Emblem', false),
  ('team', 'MAR', 'Marokko', 2, 'MAR2', 'Yassine Bounou', false),
  ('team', 'MAR', 'Marokko', 3, 'MAR3', 'Munir El Kajoui', false),
  ('team', 'MAR', 'Marokko', 4, 'MAR4', 'Achraf Hakimi', false),
  ('team', 'MAR', 'Marokko', 5, 'MAR5', 'Noussair Mazraoui', false),
  ('team', 'MAR', 'Marokko', 6, 'MAR6', 'Nayef Aguerd', false),
  ('team', 'MAR', 'Marokko', 7, 'MAR7', 'Romain Saïss', false),
  ('team', 'MAR', 'Marokko', 8, 'MAR8', 'Jawad El Yamiq', false),
  ('team', 'MAR', 'Marokko', 9, 'MAR9', 'Adam Masina', false),
  ('team', 'MAR', 'Marokko', 10, 'MAR10', 'Sofyan Amrabat', false),
  ('team', 'MAR', 'Marokko', 11, 'MAR11', 'Azzedine Ounahi', false),
  ('team', 'MAR', 'Marokko', 12, 'MAR12', 'Eliesse Ben Seghir', false),
  ('team', 'MAR', 'Marokko', 13, 'MAR13', 'Team Photo', false),
  ('team', 'MAR', 'Marokko', 14, 'MAR14', 'Bilal El Khannouss', false),
  ('team', 'MAR', 'Marokko', 15, 'MAR15', 'Ismael Saibari', false),
  ('team', 'MAR', 'Marokko', 16, 'MAR16', 'Youssef En-Nesyri', false),
  ('team', 'MAR', 'Marokko', 17, 'MAR17', 'Abde Ezzalzouli', false),
  ('team', 'MAR', 'Marokko', 18, 'MAR18', 'Soufiane Rahimi', false),
  ('team', 'MAR', 'Marokko', 19, 'MAR19', 'Brahim Diaz', false),
  ('team', 'MAR', 'Marokko', 20, 'MAR20', 'Ayoub El Kaabi', false),
  ('team', 'HAI', 'Haïti', 1, 'HAI1', 'Emblem', false),
  ('team', 'HAI', 'Haïti', 2, 'HAI2', 'Johny Placide', false),
  ('team', 'HAI', 'Haïti', 3, 'HAI3', 'Carlens Arcus', false),
  ('team', 'HAI', 'Haïti', 4, 'HAI4', 'Martin Expérience', false),
  ('team', 'HAI', 'Haïti', 5, 'HAI5', 'Jean-Kevin Duverne', false),
  ('team', 'HAI', 'Haïti', 6, 'HAI6', 'Ricardo Adé', false),
  ('team', 'HAI', 'Haïti', 7, 'HAI7', 'Duke Lacroix', false),
  ('team', 'HAI', 'Haïti', 8, 'HAI8', 'Garven Metusala', false),
  ('team', 'HAI', 'Haïti', 9, 'HAI9', 'Hannes Delcroix', false),
  ('team', 'HAI', 'Haïti', 10, 'HAI10', 'Leverton Pierre', false),
  ('team', 'HAI', 'Haïti', 11, 'HAI11', 'Danley Jean Jacques', false),
  ('team', 'HAI', 'Haïti', 12, 'HAI12', 'Jean-Ricner Bellegarde', false),
  ('team', 'HAI', 'Haïti', 13, 'HAI13', 'Team Photo', false),
  ('team', 'HAI', 'Haïti', 14, 'HAI14', 'Christopher Attys', false),
  ('team', 'HAI', 'Haïti', 15, 'HAI15', 'Derrick Etienne Jr', false),
  ('team', 'HAI', 'Haïti', 16, 'HAI16', 'Josue Casimir', false),
  ('team', 'HAI', 'Haïti', 17, 'HAI17', 'Ruben Providence', false),
  ('team', 'HAI', 'Haïti', 18, 'HAI18', 'Duckens Nazon', false),
  ('team', 'HAI', 'Haïti', 19, 'HAI19', 'Louicius Deedson', false),
  ('team', 'HAI', 'Haïti', 20, 'HAI20', 'Frantzdy Pierrot', false),
  ('team', 'SCO', 'Schotland', 1, 'SCO1', 'Emblem', false),
  ('team', 'SCO', 'Schotland', 2, 'SCO2', 'Angus Gunn', false),
  ('team', 'SCO', 'Schotland', 3, 'SCO3', 'Jack Hendry', false),
  ('team', 'SCO', 'Schotland', 4, 'SCO4', 'Kieran Tierney', false),
  ('team', 'SCO', 'Schotland', 5, 'SCO5', 'Aaron Hickey', false),
  ('team', 'SCO', 'Schotland', 6, 'SCO6', 'Andrew Robertson', false),
  ('team', 'SCO', 'Schotland', 7, 'SCO7', 'Scott McKenna', false),
  ('team', 'SCO', 'Schotland', 8, 'SCO8', 'John Souttar', false),
  ('team', 'SCO', 'Schotland', 9, 'SCO9', 'Anthony Ralston', false),
  ('team', 'SCO', 'Schotland', 10, 'SCO10', 'Grant Hanley', false),
  ('team', 'SCO', 'Schotland', 11, 'SCO11', 'Scott McTominay', false),
  ('team', 'SCO', 'Schotland', 12, 'SCO12', 'Billy Gilmour', false),
  ('team', 'SCO', 'Schotland', 13, 'SCO13', 'Team Photo', false),
  ('team', 'SCO', 'Schotland', 14, 'SCO14', 'Lewis Ferguson', false),
  ('team', 'SCO', 'Schotland', 15, 'SCO15', 'Ryan Christie', false),
  ('team', 'SCO', 'Schotland', 16, 'SCO16', 'Kenny McLean', false),
  ('team', 'SCO', 'Schotland', 17, 'SCO17', 'John McGinn', false),
  ('team', 'SCO', 'Schotland', 18, 'SCO18', 'Lyndon Dykes', false),
  ('team', 'SCO', 'Schotland', 19, 'SCO19', 'Che Adams', false),
  ('team', 'SCO', 'Schotland', 20, 'SCO20', 'Ben Gannon-Doak', false),
  ('team', 'USA', 'Verenigde Staten', 1, 'USA1', 'Emblem', false),
  ('team', 'USA', 'Verenigde Staten', 2, 'USA2', 'Matt Freese', false),
  ('team', 'USA', 'Verenigde Staten', 3, 'USA3', 'Chris Richards', false),
  ('team', 'USA', 'Verenigde Staten', 4, 'USA4', 'Tim Ream', false),
  ('team', 'USA', 'Verenigde Staten', 5, 'USA5', 'Mark McKenzie', false),
  ('team', 'USA', 'Verenigde Staten', 6, 'USA6', 'Alex Freeman', false),
  ('team', 'USA', 'Verenigde Staten', 7, 'USA7', 'Antonee Robinson', false),
  ('team', 'USA', 'Verenigde Staten', 8, 'USA8', 'Tyler Adams', false),
  ('team', 'USA', 'Verenigde Staten', 9, 'USA9', 'Tanner Tessmann', false),
  ('team', 'USA', 'Verenigde Staten', 10, 'USA10', 'Weston McKenny', false),
  ('team', 'USA', 'Verenigde Staten', 11, 'USA11', 'Christian Roldan', false),
  ('team', 'USA', 'Verenigde Staten', 12, 'USA12', 'Timothy Weah', false),
  ('team', 'USA', 'Verenigde Staten', 13, 'USA13', 'Team Photo', false),
  ('team', 'USA', 'Verenigde Staten', 14, 'USA14', 'Diego Luna', false),
  ('team', 'USA', 'Verenigde Staten', 15, 'USA15', 'Malik Tillman', false),
  ('team', 'USA', 'Verenigde Staten', 16, 'USA16', 'Christian Pulisic', false),
  ('team', 'USA', 'Verenigde Staten', 17, 'USA17', 'Brenden Aaronson', false),
  ('team', 'USA', 'Verenigde Staten', 18, 'USA18', 'Ricardo Pepi', false),
  ('team', 'USA', 'Verenigde Staten', 19, 'USA19', 'Haji Wright', false),
  ('team', 'USA', 'Verenigde Staten', 20, 'USA20', 'Folarin Balogun', false),
  ('team', 'PAR', 'Paraguay', 1, 'PAR1', 'Emblem', false),
  ('team', 'PAR', 'Paraguay', 2, 'PAR2', 'Roberto Fernandez', false),
  ('team', 'PAR', 'Paraguay', 3, 'PAR3', 'Orlando Gill', false),
  ('team', 'PAR', 'Paraguay', 4, 'PAR4', 'Gustavo Gomez', false),
  ('team', 'PAR', 'Paraguay', 5, 'PAR5', 'Fabián Balbuena', false),
  ('team', 'PAR', 'Paraguay', 6, 'PAR6', 'Juan José Cáceres', false),
  ('team', 'PAR', 'Paraguay', 7, 'PAR7', 'Omar Alderete', false),
  ('team', 'PAR', 'Paraguay', 8, 'PAR8', 'Junior Alonso', false),
  ('team', 'PAR', 'Paraguay', 9, 'PAR9', 'Mathías Villasanti', false),
  ('team', 'PAR', 'Paraguay', 10, 'PAR10', 'Diego Gomez', false),
  ('team', 'PAR', 'Paraguay', 11, 'PAR11', 'Damián Bobadilla', false),
  ('team', 'PAR', 'Paraguay', 12, 'PAR12', 'Andres Cubas', false),
  ('team', 'PAR', 'Paraguay', 13, 'PAR13', 'Team Photo', false),
  ('team', 'PAR', 'Paraguay', 14, 'PAR14', 'Matias Galarza Fonda', false),
  ('team', 'PAR', 'Paraguay', 15, 'PAR15', 'Julio Enciso', false),
  ('team', 'PAR', 'Paraguay', 16, 'PAR16', 'Alejandro Romero Gamarra', false),
  ('team', 'PAR', 'Paraguay', 17, 'PAR17', 'Miguel Almirón', false),
  ('team', 'PAR', 'Paraguay', 18, 'PAR18', 'Ramon Sosa', false),
  ('team', 'PAR', 'Paraguay', 19, 'PAR19', 'Angel Romero', false),
  ('team', 'PAR', 'Paraguay', 20, 'PAR20', 'Antonio Sanabria', false),
  ('team', 'AUS', 'Australië', 1, 'AUS1', 'Emblem', false),
  ('team', 'AUS', 'Australië', 2, 'AUS2', 'Mathew Ryan', false),
  ('team', 'AUS', 'Australië', 3, 'AUS3', 'Joe Gauci', false),
  ('team', 'AUS', 'Australië', 4, 'AUS4', 'Harry Souttar', false),
  ('team', 'AUS', 'Australië', 5, 'AUS5', 'Alessandro Circati', false),
  ('team', 'AUS', 'Australië', 6, 'AUS6', 'Jordan Bos', false),
  ('team', 'AUS', 'Australië', 7, 'AUS7', 'Aziz Behich', false),
  ('team', 'AUS', 'Australië', 8, 'AUS8', 'Cameron Burgess', false),
  ('team', 'AUS', 'Australië', 9, 'AUS9', 'Lewis Miller', false),
  ('team', 'AUS', 'Australië', 10, 'AUS10', 'Milos Degenek', false),
  ('team', 'AUS', 'Australië', 11, 'AUS11', 'Jackson Irvine', false),
  ('team', 'AUS', 'Australië', 12, 'AUS12', 'Riley McGree', false),
  ('team', 'AUS', 'Australië', 13, 'AUS13', 'Team Photo', false),
  ('team', 'AUS', 'Australië', 14, 'AUS14', 'Aiden O''Neill', false),
  ('team', 'AUS', 'Australië', 15, 'AUS15', 'Connor Metcalfe', false),
  ('team', 'AUS', 'Australië', 16, 'AUS16', 'Patrick Yazbek', false),
  ('team', 'AUS', 'Australië', 17, 'AUS17', 'Craig Goodwin', false),
  ('team', 'AUS', 'Australië', 18, 'AUS18', 'Kusini Yengi', false),
  ('team', 'AUS', 'Australië', 19, 'AUS19', 'Nestory Irankunda', false),
  ('team', 'AUS', 'Australië', 20, 'AUS20', 'Mohamed Touré', false),
  ('team', 'TUR', 'Turkije', 1, 'TUR1', 'Emblem', false),
  ('team', 'TUR', 'Turkije', 2, 'TUR2', 'Ugurcan Cakir', false),
  ('team', 'TUR', 'Turkije', 3, 'TUR3', 'Mert Muldur', false),
  ('team', 'TUR', 'Turkije', 4, 'TUR4', 'Zeki Celik', false),
  ('team', 'TUR', 'Turkije', 5, 'TUR5', 'Abdulkerim Bardakci', false),
  ('team', 'TUR', 'Turkije', 6, 'TUR6', 'Caglar Soyuncu', false),
  ('team', 'TUR', 'Turkije', 7, 'TUR7', 'Merih Demiral', false),
  ('team', 'TUR', 'Turkije', 8, 'TUR8', 'Ferdi Kadioglu', false),
  ('team', 'TUR', 'Turkije', 9, 'TUR9', 'Kaan Ayhan', false),
  ('team', 'TUR', 'Turkije', 10, 'TUR10', 'Ismail Yuksek', false),
  ('team', 'TUR', 'Turkije', 11, 'TUR11', 'Hakan Calhanoglu', false),
  ('team', 'TUR', 'Turkije', 12, 'TUR12', 'Orkun Kokcu', false),
  ('team', 'TUR', 'Turkije', 13, 'TUR13', 'Team Photo', false),
  ('team', 'TUR', 'Turkije', 14, 'TUR14', 'Arda Guler', false),
  ('team', 'TUR', 'Turkije', 15, 'TUR15', 'Irfan Can Kahveci', false),
  ('team', 'TUR', 'Turkije', 16, 'TUR16', 'Yunus Akgun', false),
  ('team', 'TUR', 'Turkije', 17, 'TUR17', 'Can Uzun', false),
  ('team', 'TUR', 'Turkije', 18, 'TUR18', 'Baris Alper Yilmaz', false),
  ('team', 'TUR', 'Turkije', 19, 'TUR19', 'Kerem Akturkoglu', false),
  ('team', 'TUR', 'Turkije', 20, 'TUR20', 'Kenan Yildiz', false),
  ('team', 'GER', 'Duitsland', 1, 'GER1', 'Emblem', false),
  ('team', 'GER', 'Duitsland', 2, 'GER2', 'Marc-André ter Stegen', false),
  ('team', 'GER', 'Duitsland', 3, 'GER3', 'Jonathan Tah', false),
  ('team', 'GER', 'Duitsland', 4, 'GER4', 'David Raum', false),
  ('team', 'GER', 'Duitsland', 5, 'GER5', 'Nico Schlotterbeck', false),
  ('team', 'GER', 'Duitsland', 6, 'GER6', 'Antonio Rüdiger', false),
  ('team', 'GER', 'Duitsland', 7, 'GER7', 'Waldemar Anton', false),
  ('team', 'GER', 'Duitsland', 8, 'GER8', 'Ridle Baku', false),
  ('team', 'GER', 'Duitsland', 9, 'GER9', 'Maximilian Mittelstadt', false),
  ('team', 'GER', 'Duitsland', 10, 'GER10', 'Joshua Kimmich', false),
  ('team', 'GER', 'Duitsland', 11, 'GER11', 'Florian Wirtz', false),
  ('team', 'GER', 'Duitsland', 12, 'GER12', 'Felix Nmecha', false),
  ('team', 'GER', 'Duitsland', 13, 'GER13', 'Team Photo', false),
  ('team', 'GER', 'Duitsland', 14, 'GER14', 'Leon Goretzka', false),
  ('team', 'GER', 'Duitsland', 15, 'GER15', 'Jamal Musiala', false),
  ('team', 'GER', 'Duitsland', 16, 'GER16', 'Serge Gnabry', false),
  ('team', 'GER', 'Duitsland', 17, 'GER17', 'Kai Havertz', false),
  ('team', 'GER', 'Duitsland', 18, 'GER18', 'Leroy Sane', false),
  ('team', 'GER', 'Duitsland', 19, 'GER19', 'Karim Adeyemi', false),
  ('team', 'GER', 'Duitsland', 20, 'GER20', 'Nick Woltemade', false),
  ('team', 'GER', 'Duitsland', 2, 'GER2s', 'Marc-André ter Stegen', true),
  ('team', 'GER', 'Duitsland', 3, 'GER3s', 'Jonathan Tah', true),
  ('team', 'GER', 'Duitsland', 4, 'GER4s', 'David Raum', true),
  ('team', 'GER', 'Duitsland', 5, 'GER5s', 'Nico Schlotterbeck', true),
  ('team', 'GER', 'Duitsland', 6, 'GER6s', 'Antonio Rüdiger', true),
  ('team', 'GER', 'Duitsland', 7, 'GER7s', 'Waldemar Anton', true),
  ('team', 'GER', 'Duitsland', 8, 'GER8s', 'Ridle Baku', true),
  ('team', 'GER', 'Duitsland', 9, 'GER9s', 'Maximilian Mittelstadt', true),
  ('team', 'GER', 'Duitsland', 10, 'GER10s', 'Joshua Kimmich', true),
  ('team', 'GER', 'Duitsland', 11, 'GER11s', 'Florian Wirtz', true),
  ('team', 'GER', 'Duitsland', 12, 'GER12s', 'Felix Nmecha', true),
  ('team', 'GER', 'Duitsland', 14, 'GER14s', 'Leon Goretzka', true),
  ('team', 'GER', 'Duitsland', 15, 'GER15s', 'Jamal Musiala', true),
  ('team', 'GER', 'Duitsland', 16, 'GER16s', 'Serge Gnabry', true),
  ('team', 'GER', 'Duitsland', 17, 'GER17s', 'Kai Havertz', true),
  ('team', 'GER', 'Duitsland', 18, 'GER18s', 'Leroy Sane', true),
  ('team', 'GER', 'Duitsland', 19, 'GER19s', 'Karim Adeyemi', true),
  ('team', 'GER', 'Duitsland', 20, 'GER20s', 'Nick Woltemade', true),
  ('team', 'CUW', 'Curaçao', 1, 'CUW1', 'Emblem', false),
  ('team', 'CUW', 'Curaçao', 2, 'CUW2', 'Eloy Room', false),
  ('team', 'CUW', 'Curaçao', 3, 'CUW3', 'Armando Obispo', false),
  ('team', 'CUW', 'Curaçao', 4, 'CUW4', 'Sherel Floranus', false),
  ('team', 'CUW', 'Curaçao', 5, 'CUW5', 'Jurien Gaari', false),
  ('team', 'CUW', 'Curaçao', 6, 'CUW6', 'Joshua Brenet', false),
  ('team', 'CUW', 'Curaçao', 7, 'CUW7', 'Roshon Van Eijma', false),
  ('team', 'CUW', 'Curaçao', 8, 'CUW8', 'Shurandy Sambo', false),
  ('team', 'CUW', 'Curaçao', 9, 'CUW9', 'Livano Comenencia', false),
  ('team', 'CUW', 'Curaçao', 10, 'CUW10', 'Godfried Roemeratoe', false),
  ('team', 'CUW', 'Curaçao', 11, 'CUW11', 'Juninho Bacuna', false),
  ('team', 'CUW', 'Curaçao', 12, 'CUW12', 'Leandro Bacuna', false),
  ('team', 'CUW', 'Curaçao', 13, 'CUW13', 'Team Photo', false),
  ('team', 'CUW', 'Curaçao', 14, 'CUW14', 'Tahith Chong', false),
  ('team', 'CUW', 'Curaçao', 15, 'CUW15', 'Kenji Gorre', false),
  ('team', 'CUW', 'Curaçao', 16, 'CUW16', 'Jearl Margaritha', false),
  ('team', 'CUW', 'Curaçao', 17, 'CUW17', 'Jurgen Locadia', false),
  ('team', 'CUW', 'Curaçao', 18, 'CUW18', 'Jeremy Antonisse', false),
  ('team', 'CUW', 'Curaçao', 19, 'CUW19', 'Gervane Kastaneer', false),
  ('team', 'CUW', 'Curaçao', 20, 'CUW20', 'Sontje Hansen', false),
  ('team', 'CIV', 'Ivoorkust', 1, 'CIV1', 'Emblem', false),
  ('team', 'CIV', 'Ivoorkust', 2, 'CIV2', 'Yahia Fofana', false),
  ('team', 'CIV', 'Ivoorkust', 3, 'CIV3', 'Ghislain Konan', false),
  ('team', 'CIV', 'Ivoorkust', 4, 'CIV4', 'Wilfried Singo', false),
  ('team', 'CIV', 'Ivoorkust', 5, 'CIV5', 'Odilon Kossounou', false),
  ('team', 'CIV', 'Ivoorkust', 6, 'CIV6', 'Evan Ndicka', false),
  ('team', 'CIV', 'Ivoorkust', 7, 'CIV7', 'Willy Boly', false),
  ('team', 'CIV', 'Ivoorkust', 8, 'CIV8', 'Emmanuel Agbadou', false),
  ('team', 'CIV', 'Ivoorkust', 9, 'CIV9', 'Ousmane Diomande', false),
  ('team', 'CIV', 'Ivoorkust', 10, 'CIV10', 'Franck Kessie', false),
  ('team', 'CIV', 'Ivoorkust', 11, 'CIV11', 'Seko Fofana', false),
  ('team', 'CIV', 'Ivoorkust', 12, 'CIV12', 'Ibrahim Sangare', false),
  ('team', 'CIV', 'Ivoorkust', 13, 'CIV13', 'Team Photo', false),
  ('team', 'CIV', 'Ivoorkust', 14, 'CIV14', 'Jean-Philippe Gbamin', false),
  ('team', 'CIV', 'Ivoorkust', 15, 'CIV15', 'Amad Diallo', false),
  ('team', 'CIV', 'Ivoorkust', 16, 'CIV16', 'Sébastien Haller', false),
  ('team', 'CIV', 'Ivoorkust', 17, 'CIV17', 'Simon Adingra', false),
  ('team', 'CIV', 'Ivoorkust', 18, 'CIV18', 'Yan Diomande', false),
  ('team', 'CIV', 'Ivoorkust', 19, 'CIV19', 'Evann Guessand', false),
  ('team', 'CIV', 'Ivoorkust', 20, 'CIV20', 'Oumar Diakite', false),
  ('team', 'ECU', 'Ecuador', 1, 'ECU1', 'Emblem', false),
  ('team', 'ECU', 'Ecuador', 2, 'ECU2', 'Hernán Galíndez', false),
  ('team', 'ECU', 'Ecuador', 3, 'ECU3', 'Gonzalo Valle', false),
  ('team', 'ECU', 'Ecuador', 4, 'ECU4', 'Piero Hincapié', false),
  ('team', 'ECU', 'Ecuador', 5, 'ECU5', 'Pervis Estupiñán', false),
  ('team', 'ECU', 'Ecuador', 6, 'ECU6', 'Willian Pacho', false),
  ('team', 'ECU', 'Ecuador', 7, 'ECU7', 'Ángelo Preciado', false),
  ('team', 'ECU', 'Ecuador', 8, 'ECU8', 'Joel Ordóñez', false),
  ('team', 'ECU', 'Ecuador', 9, 'ECU9', 'Moises Caicedo', false),
  ('team', 'ECU', 'Ecuador', 10, 'ECU10', 'Alan Franco', false),
  ('team', 'ECU', 'Ecuador', 11, 'ECU11', 'Kendry Paez', false),
  ('team', 'ECU', 'Ecuador', 12, 'ECU12', 'Pedro Vite', false),
  ('team', 'ECU', 'Ecuador', 13, 'ECU13', 'Team Photo', false),
  ('team', 'ECU', 'Ecuador', 14, 'ECU14', 'John Yeboah', false),
  ('team', 'ECU', 'Ecuador', 15, 'ECU15', 'Leonardo Campana', false),
  ('team', 'ECU', 'Ecuador', 16, 'ECU16', 'Gonzalo Plata', false),
  ('team', 'ECU', 'Ecuador', 17, 'ECU17', 'Nilson Angulo', false),
  ('team', 'ECU', 'Ecuador', 18, 'ECU18', 'Alan Minda', false),
  ('team', 'ECU', 'Ecuador', 19, 'ECU19', 'Kevin Rodriguez', false),
  ('team', 'ECU', 'Ecuador', 20, 'ECU20', 'Enner Valencia', false),
  ('team', 'NED', 'Nederland', 1, 'NED1', 'Emblem', false),
  ('team', 'NED', 'Nederland', 2, 'NED2', 'Bart Verbruggen', false),
  ('team', 'NED', 'Nederland', 3, 'NED3', 'Virgil van Dijk', false),
  ('team', 'NED', 'Nederland', 4, 'NED4', 'Micky van de Ven', false),
  ('team', 'NED', 'Nederland', 5, 'NED5', 'Jurrien Timber', false),
  ('team', 'NED', 'Nederland', 6, 'NED6', 'Denzel Dumfries', false),
  ('team', 'NED', 'Nederland', 7, 'NED7', 'Nathan Aké', false),
  ('team', 'NED', 'Nederland', 8, 'NED8', 'Jeremie Frimpong', false),
  ('team', 'NED', 'Nederland', 9, 'NED9', 'Jan Paul van Hecke', false),
  ('team', 'NED', 'Nederland', 10, 'NED10', 'Tijjani Reijnders', false),
  ('team', 'NED', 'Nederland', 11, 'NED11', 'Ryan Gravenberch', false),
  ('team', 'NED', 'Nederland', 12, 'NED12', 'Teun Koopmeiners', false),
  ('team', 'NED', 'Nederland', 13, 'NED13', 'Team Photo', false),
  ('team', 'NED', 'Nederland', 14, 'NED14', 'Frenkie de Jong', false),
  ('team', 'NED', 'Nederland', 15, 'NED15', 'Xavi Simons', false),
  ('team', 'NED', 'Nederland', 16, 'NED16', 'Justin Kluivert', false),
  ('team', 'NED', 'Nederland', 17, 'NED17', 'Memphis Depay', false),
  ('team', 'NED', 'Nederland', 18, 'NED18', 'Donyell Malen', false),
  ('team', 'NED', 'Nederland', 19, 'NED19', 'Wout Weghorst', false),
  ('team', 'NED', 'Nederland', 20, 'NED20', 'Cody Gakpo', false),
  ('team', 'JPN', 'Japan', 1, 'JPN1', 'Emblem', false),
  ('team', 'JPN', 'Japan', 2, 'JPN2', 'Zion Suzuki', false),
  ('team', 'JPN', 'Japan', 3, 'JPN3', 'Henry Heroki Mochizuki', false),
  ('team', 'JPN', 'Japan', 4, 'JPN4', 'Ayumu Seko', false),
  ('team', 'JPN', 'Japan', 5, 'JPN5', 'Junnosuke Suzuki', false),
  ('team', 'JPN', 'Japan', 6, 'JPN6', 'Shogo Taniguchi', false),
  ('team', 'JPN', 'Japan', 7, 'JPN7', 'Tsuyoshi Watanabe', false),
  ('team', 'JPN', 'Japan', 8, 'JPN8', 'Kaishu Sano', false),
  ('team', 'JPN', 'Japan', 9, 'JPN9', 'Yuki Soma', false),
  ('team', 'JPN', 'Japan', 10, 'JPN10', 'Ao Tanaka', false),
  ('team', 'JPN', 'Japan', 11, 'JPN11', 'Daichi Kamada', false),
  ('team', 'JPN', 'Japan', 12, 'JPN12', 'Takefusa Kubo', false),
  ('team', 'JPN', 'Japan', 13, 'JPN13', 'Team Photo', false),
  ('team', 'JPN', 'Japan', 14, 'JPN14', 'Ritsu Doan', false),
  ('team', 'JPN', 'Japan', 15, 'JPN15', 'Keito Nakamura', false),
  ('team', 'JPN', 'Japan', 16, 'JPN16', 'Takumi Minamino', false),
  ('team', 'JPN', 'Japan', 17, 'JPN17', 'Shuto Machino', false),
  ('team', 'JPN', 'Japan', 18, 'JPN18', 'Junya Ito', false),
  ('team', 'JPN', 'Japan', 19, 'JPN19', 'Koki Ogawa', false),
  ('team', 'JPN', 'Japan', 20, 'JPN20', 'Ayase Ueda', false),
  ('team', 'SWE', 'Zweden', 1, 'SWE1', 'Emblem', false),
  ('team', 'SWE', 'Zweden', 2, 'SWE2', 'Victor Johansson', false),
  ('team', 'SWE', 'Zweden', 3, 'SWE3', 'Isak Hien', false),
  ('team', 'SWE', 'Zweden', 4, 'SWE4', 'Gabriel Gudmundsson', false),
  ('team', 'SWE', 'Zweden', 5, 'SWE5', 'Emil Holm', false),
  ('team', 'SWE', 'Zweden', 6, 'SWE6', 'Victor Nilsson Lindelöf', false),
  ('team', 'SWE', 'Zweden', 7, 'SWE7', 'Gustaf Lagerbielke', false),
  ('team', 'SWE', 'Zweden', 8, 'SWE8', 'Lucas Bergvall', false),
  ('team', 'SWE', 'Zweden', 9, 'SWE9', 'Hugo Larsson', false),
  ('team', 'SWE', 'Zweden', 10, 'SWE10', 'Jesper Karlström', false),
  ('team', 'SWE', 'Zweden', 11, 'SWE11', 'Yasin Ayari', false),
  ('team', 'SWE', 'Zweden', 12, 'SWE12', 'Mattias Svanberg', false),
  ('team', 'SWE', 'Zweden', 13, 'SWE13', 'Team Photo', false),
  ('team', 'SWE', 'Zweden', 14, 'SWE14', 'Daniel Svensson', false),
  ('team', 'SWE', 'Zweden', 15, 'SWE15', 'Ken Sema', false),
  ('team', 'SWE', 'Zweden', 16, 'SWE16', 'Roony Bardghji', false),
  ('team', 'SWE', 'Zweden', 17, 'SWE17', 'Dejan Kulusevski', false),
  ('team', 'SWE', 'Zweden', 18, 'SWE18', 'Anthony Elanga', false),
  ('team', 'SWE', 'Zweden', 19, 'SWE19', 'Alexander Isak', false),
  ('team', 'SWE', 'Zweden', 20, 'SWE20', 'Viktor Gyökeres', false),
  ('team', 'TUN', 'Tunesië', 1, 'TUN1', 'Emblem', false),
  ('team', 'TUN', 'Tunesië', 2, 'TUN2', 'Bechir Ben Said', false),
  ('team', 'TUN', 'Tunesië', 3, 'TUN3', 'Aymen Dahmen', false),
  ('team', 'TUN', 'Tunesië', 4, 'TUN4', 'Yan Valery', false),
  ('team', 'TUN', 'Tunesië', 5, 'TUN5', 'Montassar Talbi', false),
  ('team', 'TUN', 'Tunesië', 6, 'TUN6', 'Yassine Meriah', false),
  ('team', 'TUN', 'Tunesië', 7, 'TUN7', 'Ali Abdi', false),
  ('team', 'TUN', 'Tunesië', 8, 'TUN8', 'Dylan Bronn', false),
  ('team', 'TUN', 'Tunesië', 9, 'TUN9', 'Ellyes Skhiri', false),
  ('team', 'TUN', 'Tunesië', 10, 'TUN10', 'Aissa Laidouni', false),
  ('team', 'TUN', 'Tunesië', 11, 'TUN11', 'Ferjani Sassi', false),
  ('team', 'TUN', 'Tunesië', 12, 'TUN12', 'Mohamed Ali Ben Romdhane', false),
  ('team', 'TUN', 'Tunesië', 13, 'TUN13', 'Team Photo', false),
  ('team', 'TUN', 'Tunesië', 14, 'TUN14', 'Hannibal Mejbri', false),
  ('team', 'TUN', 'Tunesië', 15, 'TUN15', 'Elias Achouri', false),
  ('team', 'TUN', 'Tunesië', 16, 'TUN16', 'Elias Saad', false),
  ('team', 'TUN', 'Tunesië', 17, 'TUN17', 'Hazem Mastouri', false),
  ('team', 'TUN', 'Tunesië', 18, 'TUN18', 'Ismael Gharbi', false),
  ('team', 'TUN', 'Tunesië', 19, 'TUN19', 'Sayfallah Ltaief', false),
  ('team', 'TUN', 'Tunesië', 20, 'TUN20', 'Naim Sliti', false),
  ('team', 'BEL', 'België', 1, 'BEL1', 'Emblem', false),
  ('team', 'BEL', 'België', 2, 'BEL2', 'Thibaut Courtois', false),
  ('team', 'BEL', 'België', 3, 'BEL3', 'Arthur Theate', false),
  ('team', 'BEL', 'België', 4, 'BEL4', 'Timothy Castagne', false),
  ('team', 'BEL', 'België', 5, 'BEL5', 'Zeno Debast', false),
  ('team', 'BEL', 'België', 6, 'BEL6', 'Brandon Mechele', false),
  ('team', 'BEL', 'België', 7, 'BEL7', 'Maxim De Cuyper', false),
  ('team', 'BEL', 'België', 8, 'BEL8', 'Thomas Meunier', false),
  ('team', 'BEL', 'België', 9, 'BEL9', 'Youri Tielemans', false),
  ('team', 'BEL', 'België', 10, 'BEL10', 'Amadou Onana', false),
  ('team', 'BEL', 'België', 11, 'BEL11', 'Nicolas Raskin', false),
  ('team', 'BEL', 'België', 12, 'BEL12', 'Alexis Saelemaekers', false),
  ('team', 'BEL', 'België', 13, 'BEL13', 'Team Photo', false),
  ('team', 'BEL', 'België', 14, 'BEL14', 'Hans Vanaken', false),
  ('team', 'BEL', 'België', 15, 'BEL15', 'Kevin De Bruyne', false),
  ('team', 'BEL', 'België', 16, 'BEL16', 'Jérémy Doku', false),
  ('team', 'BEL', 'België', 17, 'BEL17', 'Charles De Ketelaere', false),
  ('team', 'BEL', 'België', 18, 'BEL18', 'Leandro Trossard', false),
  ('team', 'BEL', 'België', 19, 'BEL19', 'Loïs Openda', false),
  ('team', 'BEL', 'België', 20, 'BEL20', 'Romelu Lukaku', false),
  ('team', 'BEL', 'België', 2, 'BEL2s', 'Thibaut Courtois', true),
  ('team', 'BEL', 'België', 3, 'BEL3s', 'Arthur Theate', true),
  ('team', 'BEL', 'België', 4, 'BEL4s', 'Timothy Castagne', true),
  ('team', 'BEL', 'België', 5, 'BEL5s', 'Zeno Debast', true),
  ('team', 'BEL', 'België', 6, 'BEL6s', 'Brandon Mechele', true),
  ('team', 'BEL', 'België', 7, 'BEL7s', 'Maxim De Cuyper', true),
  ('team', 'BEL', 'België', 8, 'BEL8s', 'Thomas Meunier', true),
  ('team', 'BEL', 'België', 9, 'BEL9s', 'Youri Tielemans', true),
  ('team', 'BEL', 'België', 10, 'BEL10s', 'Amadou Onana', true),
  ('team', 'BEL', 'België', 11, 'BEL11s', 'Nicolas Raskin', true),
  ('team', 'BEL', 'België', 12, 'BEL12s', 'Alexis Saelemaekers', true),
  ('team', 'BEL', 'België', 14, 'BEL14s', 'Hans Vanaken', true),
  ('team', 'BEL', 'België', 15, 'BEL15s', 'Kevin De Bruyne', true),
  ('team', 'BEL', 'België', 16, 'BEL16s', 'Jérémy Doku', true),
  ('team', 'BEL', 'België', 17, 'BEL17s', 'Charles De Ketelaere', true),
  ('team', 'BEL', 'België', 18, 'BEL18s', 'Leandro Trossard', true),
  ('team', 'BEL', 'België', 19, 'BEL19s', 'Loïs Openda', true),
  ('team', 'BEL', 'België', 20, 'BEL20s', 'Romelu Lukaku', true),
  ('team', 'EGY', 'Egypte', 1, 'EGY1', 'Emblem', false),
  ('team', 'EGY', 'Egypte', 2, 'EGY2', 'Mohamed El Shenawy', false),
  ('team', 'EGY', 'Egypte', 3, 'EGY3', 'Mohamed Hany', false),
  ('team', 'EGY', 'Egypte', 4, 'EGY4', 'Mohamed Hamdy', false),
  ('team', 'EGY', 'Egypte', 5, 'EGY5', 'Yasser Ibrahim', false),
  ('team', 'EGY', 'Egypte', 6, 'EGY6', 'Khaled Sobhi', false),
  ('team', 'EGY', 'Egypte', 7, 'EGY7', 'Ramy Rabia', false),
  ('team', 'EGY', 'Egypte', 8, 'EGY8', 'Hossam Abdelmaguid', false),
  ('team', 'EGY', 'Egypte', 9, 'EGY9', 'Ahmed Fatouh', false),
  ('team', 'EGY', 'Egypte', 10, 'EGY10', 'Marwan Attia', false),
  ('team', 'EGY', 'Egypte', 11, 'EGY11', 'Zizo', false),
  ('team', 'EGY', 'Egypte', 12, 'EGY12', 'Hamdy Fathy', false),
  ('team', 'EGY', 'Egypte', 13, 'EGY13', 'Team Photo', false),
  ('team', 'EGY', 'Egypte', 14, 'EGY14', 'Mohamed Lasheen', false),
  ('team', 'EGY', 'Egypte', 15, 'EGY15', 'Emam Ashour', false),
  ('team', 'EGY', 'Egypte', 16, 'EGY16', 'Osama Faisal', false),
  ('team', 'EGY', 'Egypte', 17, 'EGY17', 'Mohamed Salah', false),
  ('team', 'EGY', 'Egypte', 18, 'EGY18', 'Mostafa Mohamed', false),
  ('team', 'EGY', 'Egypte', 19, 'EGY19', 'Trezeguet', false),
  ('team', 'EGY', 'Egypte', 20, 'EGY20', 'Omar Marmoush', false),
  ('team', 'IRN', 'Iran', 1, 'IRN1', 'Emblem', false),
  ('team', 'IRN', 'Iran', 2, 'IRN2', 'Alireza Beiranvand', false),
  ('team', 'IRN', 'Iran', 3, 'IRN3', 'Morteza Pouraliganji', false),
  ('team', 'IRN', 'Iran', 4, 'IRN4', 'Ehsan Hajsafi', false),
  ('team', 'IRN', 'Iran', 5, 'IRN5', 'Milad Mohammadi', false),
  ('team', 'IRN', 'Iran', 6, 'IRN6', 'Shojae Khalilzadeh', false),
  ('team', 'IRN', 'Iran', 7, 'IRN7', 'Ramin Rezaeian', false),
  ('team', 'IRN', 'Iran', 8, 'IRN8', 'Hossein Kanaani', false),
  ('team', 'IRN', 'Iran', 9, 'IRN9', 'Sadegh Moharrami', false),
  ('team', 'IRN', 'Iran', 10, 'IRN10', 'Saleh Hardani', false),
  ('team', 'IRN', 'Iran', 11, 'IRN11', 'Saeed Ezatolahi', false),
  ('team', 'IRN', 'Iran', 12, 'IRN12', 'Saman Ghoddos', false),
  ('team', 'IRN', 'Iran', 13, 'IRN13', 'Team Photo', false),
  ('team', 'IRN', 'Iran', 14, 'IRN14', 'Omid Noorafkan', false),
  ('team', 'IRN', 'Iran', 15, 'IRN15', 'Roozbeh Cheshmi', false),
  ('team', 'IRN', 'Iran', 16, 'IRN16', 'Mohammad Mohebi', false),
  ('team', 'IRN', 'Iran', 17, 'IRN17', 'Sardar Azmoun', false),
  ('team', 'IRN', 'Iran', 18, 'IRN18', 'Mehdi Taremi', false),
  ('team', 'IRN', 'Iran', 19, 'IRN19', 'Alireza Jahanbakhsh', false),
  ('team', 'IRN', 'Iran', 20, 'IRN20', 'Ali Gholizadeh', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 1, 'NZL1', 'Emblem', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 2, 'NZL2', 'Max Crocombe', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 3, 'NZL3', 'Alex Paulsen', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 4, 'NZL4', 'Michael Boxall', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 5, 'NZL5', 'Liberato Cacace', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 6, 'NZL6', 'Tim Payne', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 7, 'NZL7', 'Tyler Bindon', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 8, 'NZL8', 'Francis de Vries', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 9, 'NZL9', 'Finn Surman', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 10, 'NZL10', 'Joe Bell', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 11, 'NZL11', 'Sarpreet Singh', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 12, 'NZL12', 'Ryan Thomas', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 13, 'NZL13', 'Team Photo', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 14, 'NZL14', 'Matthew Garbett', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 15, 'NZL15', 'Marko Stamenić', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 16, 'NZL16', 'Ben Old', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 17, 'NZL17', 'Chris Wood', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 18, 'NZL18', 'Elijah Just', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 19, 'NZL19', 'Callum McCowatt', false),
  ('team', 'NZL', 'Nieuw-Zeeland', 20, 'NZL20', 'Kosta Barbarouses', false),
  ('team', 'ESP', 'Spanje', 1, 'ESP1', 'Emblem', false),
  ('team', 'ESP', 'Spanje', 2, 'ESP2', 'Unai Simon', false),
  ('team', 'ESP', 'Spanje', 3, 'ESP3', 'Robin Le Normand', false),
  ('team', 'ESP', 'Spanje', 4, 'ESP4', 'Aymeric Laporte', false),
  ('team', 'ESP', 'Spanje', 5, 'ESP5', 'Dean Huijsen', false),
  ('team', 'ESP', 'Spanje', 6, 'ESP6', 'Pedro Porro', false),
  ('team', 'ESP', 'Spanje', 7, 'ESP7', 'Dani Carvajal', false),
  ('team', 'ESP', 'Spanje', 8, 'ESP8', 'Marc Cucurella', false),
  ('team', 'ESP', 'Spanje', 9, 'ESP9', 'Martín Zubimendi', false),
  ('team', 'ESP', 'Spanje', 10, 'ESP10', 'Rodri', false),
  ('team', 'ESP', 'Spanje', 11, 'ESP11', 'Pedri', false),
  ('team', 'ESP', 'Spanje', 12, 'ESP12', 'Fabian Ruiz', false),
  ('team', 'ESP', 'Spanje', 13, 'ESP13', 'Team Photo', false),
  ('team', 'ESP', 'Spanje', 14, 'ESP14', 'Mikel Merino', false),
  ('team', 'ESP', 'Spanje', 15, 'ESP15', 'Lamine Yamal', false),
  ('team', 'ESP', 'Spanje', 16, 'ESP16', 'Dani Olmo', false),
  ('team', 'ESP', 'Spanje', 17, 'ESP17', 'Nico Williams', false),
  ('team', 'ESP', 'Spanje', 18, 'ESP18', 'Ferran Torres', false),
  ('team', 'ESP', 'Spanje', 19, 'ESP19', 'Álvaro Morata', false),
  ('team', 'ESP', 'Spanje', 20, 'ESP20', 'Mikel Oyarzabal', false),
  ('team', 'CPV', 'Kaapverdië', 1, 'CPV1', 'Emblem', false),
  ('team', 'CPV', 'Kaapverdië', 2, 'CPV2', 'Vozinha', false),
  ('team', 'CPV', 'Kaapverdië', 3, 'CPV3', 'Logan Costa', false),
  ('team', 'CPV', 'Kaapverdië', 4, 'CPV4', 'Pico', false),
  ('team', 'CPV', 'Kaapverdië', 5, 'CPV5', 'Diney', false),
  ('team', 'CPV', 'Kaapverdië', 6, 'CPV6', 'Steven Moreira', false),
  ('team', 'CPV', 'Kaapverdië', 7, 'CPV7', 'Wagner Pina', false),
  ('team', 'CPV', 'Kaapverdië', 8, 'CPV8', 'Joao Paulo', false),
  ('team', 'CPV', 'Kaapverdië', 9, 'CPV9', 'Yannick Semedo', false),
  ('team', 'CPV', 'Kaapverdië', 10, 'CPV10', 'Kevin Pina', false),
  ('team', 'CPV', 'Kaapverdië', 11, 'CPV11', 'Patrick Andrade', false),
  ('team', 'CPV', 'Kaapverdië', 12, 'CPV12', 'Jamiro Monteiro', false),
  ('team', 'CPV', 'Kaapverdië', 13, 'CPV13', 'Team Photo', false),
  ('team', 'CPV', 'Kaapverdië', 14, 'CPV14', 'Deroy Duarte', false),
  ('team', 'CPV', 'Kaapverdië', 15, 'CPV15', 'Garry Rodrigues', false),
  ('team', 'CPV', 'Kaapverdië', 16, 'CPV16', 'Jovane Cabral', false),
  ('team', 'CPV', 'Kaapverdië', 17, 'CPV17', 'Ryan Mendes', false),
  ('team', 'CPV', 'Kaapverdië', 18, 'CPV18', 'Dailon Livramento', false),
  ('team', 'CPV', 'Kaapverdië', 19, 'CPV19', 'Willy Semedo', false),
  ('team', 'CPV', 'Kaapverdië', 20, 'CPV20', 'Bebe', false),
  ('team', 'KSA', 'Saoedi-Arabië', 1, 'KSA1', 'Emblem', false),
  ('team', 'KSA', 'Saoedi-Arabië', 2, 'KSA2', 'Nawaf Alaqidi', false),
  ('team', 'KSA', 'Saoedi-Arabië', 3, 'KSA3', 'Abdulrahman Al-Sanbi', false),
  ('team', 'KSA', 'Saoedi-Arabië', 4, 'KSA4', 'Saud Abdulhamid', false),
  ('team', 'KSA', 'Saoedi-Arabië', 5, 'KSA5', 'Nawaf Bouwashl', false),
  ('team', 'KSA', 'Saoedi-Arabië', 6, 'KSA6', 'Jihad Thakri', false),
  ('team', 'KSA', 'Saoedi-Arabië', 7, 'KSA7', 'Moteb Al-Harbi', false),
  ('team', 'KSA', 'Saoedi-Arabië', 8, 'KSA8', 'Hassan Altambakti', false),
  ('team', 'KSA', 'Saoedi-Arabië', 9, 'KSA9', 'Musab Aljuwayr', false),
  ('team', 'KSA', 'Saoedi-Arabië', 10, 'KSA10', 'Ziyad Aljohani', false),
  ('team', 'KSA', 'Saoedi-Arabië', 11, 'KSA11', 'Abdullah Alkhaibari', false),
  ('team', 'KSA', 'Saoedi-Arabië', 12, 'KSA12', 'Nasser Aldawsari', false),
  ('team', 'KSA', 'Saoedi-Arabië', 13, 'KSA13', 'Team Photo', false),
  ('team', 'KSA', 'Saoedi-Arabië', 14, 'KSA14', 'Saleh Abu Alshamat', false),
  ('team', 'KSA', 'Saoedi-Arabië', 15, 'KSA15', 'Marwan Alsahafi', false),
  ('team', 'KSA', 'Saoedi-Arabië', 16, 'KSA16', 'Salem Aldawsari', false),
  ('team', 'KSA', 'Saoedi-Arabië', 17, 'KSA17', 'Abdulrahman Al-Aboud', false),
  ('team', 'KSA', 'Saoedi-Arabië', 18, 'KSA18', 'Feras Akbrikan', false),
  ('team', 'KSA', 'Saoedi-Arabië', 19, 'KSA19', 'Saleh Alshehri', false),
  ('team', 'KSA', 'Saoedi-Arabië', 20, 'KSA20', 'Abdullah Al-Hamdan', false),
  ('team', 'URU', 'Uruguay', 1, 'URU1', 'Emblem', false),
  ('team', 'URU', 'Uruguay', 2, 'URU2', 'Sergio Rochet', false),
  ('team', 'URU', 'Uruguay', 3, 'URU3', 'Santiago Mele', false),
  ('team', 'URU', 'Uruguay', 4, 'URU4', 'Ronald Araujo', false),
  ('team', 'URU', 'Uruguay', 5, 'URU5', 'José María Giménez', false),
  ('team', 'URU', 'Uruguay', 6, 'URU6', 'Sebastian Caceres', false),
  ('team', 'URU', 'Uruguay', 7, 'URU7', 'Mathias Olivera', false),
  ('team', 'URU', 'Uruguay', 8, 'URU8', 'Guillermo Varela', false),
  ('team', 'URU', 'Uruguay', 9, 'URU9', 'Nahitan Nandez', false),
  ('team', 'URU', 'Uruguay', 10, 'URU10', 'Federico Valverde', false),
  ('team', 'URU', 'Uruguay', 11, 'URU11', 'Giorgian De Arrascaeta', false),
  ('team', 'URU', 'Uruguay', 12, 'URU12', 'Rodrigo Bentancur', false),
  ('team', 'URU', 'Uruguay', 13, 'URU13', 'Team Photo', false),
  ('team', 'URU', 'Uruguay', 14, 'URU14', 'Manuel Ugarte', false),
  ('team', 'URU', 'Uruguay', 15, 'URU15', 'Nicolás de la Cruz', false),
  ('team', 'URU', 'Uruguay', 16, 'URU16', 'Maxi Araujo', false),
  ('team', 'URU', 'Uruguay', 17, 'URU17', 'Darwin Núñez', false),
  ('team', 'URU', 'Uruguay', 18, 'URU18', 'Federico Viñas', false),
  ('team', 'URU', 'Uruguay', 19, 'URU19', 'Rodrigo Aguirre', false),
  ('team', 'URU', 'Uruguay', 20, 'URU20', 'Facundo Pellistri', false),
  ('team', 'FRA', 'Frankrijk', 1, 'FRA1', 'Emblem', false),
  ('team', 'FRA', 'Frankrijk', 2, 'FRA2', 'Mike Maignan', false),
  ('team', 'FRA', 'Frankrijk', 3, 'FRA3', 'Theo Hernandez', false),
  ('team', 'FRA', 'Frankrijk', 4, 'FRA4', 'William Saliba', false),
  ('team', 'FRA', 'Frankrijk', 5, 'FRA5', 'Jules Kounde', false),
  ('team', 'FRA', 'Frankrijk', 6, 'FRA6', 'Ibrahima Konate', false),
  ('team', 'FRA', 'Frankrijk', 7, 'FRA7', 'Dayot Upamecano', false),
  ('team', 'FRA', 'Frankrijk', 8, 'FRA8', 'Lucas Digne', false),
  ('team', 'FRA', 'Frankrijk', 9, 'FRA9', 'Aurélien Tchouaméni', false),
  ('team', 'FRA', 'Frankrijk', 10, 'FRA10', 'Eduardo Camavinga', false),
  ('team', 'FRA', 'Frankrijk', 11, 'FRA11', 'Manu Kone', false),
  ('team', 'FRA', 'Frankrijk', 12, 'FRA12', 'Adrien Rabiot', false),
  ('team', 'FRA', 'Frankrijk', 13, 'FRA13', 'Team Photo', false),
  ('team', 'FRA', 'Frankrijk', 14, 'FRA14', 'Michael Olise', false),
  ('team', 'FRA', 'Frankrijk', 15, 'FRA15', 'Ousmane Dembele', false),
  ('team', 'FRA', 'Frankrijk', 16, 'FRA16', 'Bradley Barcola', false),
  ('team', 'FRA', 'Frankrijk', 17, 'FRA17', 'Désiré Doué', false),
  ('team', 'FRA', 'Frankrijk', 18, 'FRA18', 'Kingsley Coman', false),
  ('team', 'FRA', 'Frankrijk', 19, 'FRA19', 'Hugo Ekitike', false),
  ('team', 'FRA', 'Frankrijk', 2, 'FRA2s', 'Mike Maignan', true),
  ('team', 'FRA', 'Frankrijk', 3, 'FRA3s', 'Theo Hernandez', true),
  ('team', 'FRA', 'Frankrijk', 4, 'FRA4s', 'William Saliba', true),
  ('team', 'FRA', 'Frankrijk', 5, 'FRA5s', 'Jules Kounde', true),
  ('team', 'FRA', 'Frankrijk', 6, 'FRA6s', 'Ibrahima Konate', true),
  ('team', 'FRA', 'Frankrijk', 7, 'FRA7s', 'Dayot Upamecano', true),
  ('team', 'FRA', 'Frankrijk', 8, 'FRA8s', 'Lucas Digne', true),
  ('team', 'FRA', 'Frankrijk', 9, 'FRA9s', 'Aurélien Tchouaméni', true),
  ('team', 'FRA', 'Frankrijk', 10, 'FRA10s', 'Eduardo Camavinga', true),
  ('team', 'FRA', 'Frankrijk', 11, 'FRA11s', 'Manu Kone', true),
  ('team', 'FRA', 'Frankrijk', 12, 'FRA12s', 'Adrien Rabiot', true),
  ('team', 'FRA', 'Frankrijk', 14, 'FRA14s', 'Michael Olise', true),
  ('team', 'FRA', 'Frankrijk', 15, 'FRA15s', 'Ousmane Dembele', true),
  ('team', 'FRA', 'Frankrijk', 16, 'FRA16s', 'Bradley Barcola', true),
  ('team', 'FRA', 'Frankrijk', 17, 'FRA17s', 'Désiré Doué', true),
  ('team', 'FRA', 'Frankrijk', 18, 'FRA18s', 'Kingsley Coman', true),
  ('team', 'FRA', 'Frankrijk', 19, 'FRA19s', 'Hugo Ekitike', true),
  ('team', 'FRA', 'Frankrijk', 20, 'FRA20', 'Kylian Mbappe', false),
  ('team', 'FRA', 'Frankrijk', 20, 'FRA20s', 'Kylian Mbappe', true),
  ('team', 'SEN', 'Senegal', 1, 'SEN1', 'Emblem', false),
  ('team', 'SEN', 'Senegal', 2, 'SEN2', 'Édouard Mendy', false),
  ('team', 'SEN', 'Senegal', 3, 'SEN3', 'Yehvann Diouf', false),
  ('team', 'SEN', 'Senegal', 4, 'SEN4', 'Moussa Niakhaté', false),
  ('team', 'SEN', 'Senegal', 5, 'SEN5', 'Abdoulaye Seck', false),
  ('team', 'SEN', 'Senegal', 6, 'SEN6', 'Ismail Jakobs', false),
  ('team', 'SEN', 'Senegal', 7, 'SEN7', 'El Hadji Malick Diouf', false),
  ('team', 'SEN', 'Senegal', 8, 'SEN8', 'Kalidou Koulibaly', false),
  ('team', 'SEN', 'Senegal', 9, 'SEN9', 'Idrissa Gana Gueye', false),
  ('team', 'SEN', 'Senegal', 10, 'SEN10', 'Pape Matar Sarr', false),
  ('team', 'SEN', 'Senegal', 11, 'SEN11', 'Pape Gueye', false),
  ('team', 'SEN', 'Senegal', 12, 'SEN12', 'Habib Diarra', false),
  ('team', 'SEN', 'Senegal', 13, 'SEN13', 'Team Photo', false),
  ('team', 'SEN', 'Senegal', 14, 'SEN14', 'Lamine Camara', false),
  ('team', 'SEN', 'Senegal', 15, 'SEN15', 'Sadio Mane', false),
  ('team', 'SEN', 'Senegal', 16, 'SEN16', 'Ismaïla Sarr', false),
  ('team', 'SEN', 'Senegal', 17, 'SEN17', 'Boulaye Dia', false),
  ('team', 'SEN', 'Senegal', 18, 'SEN18', 'Iliman Ndiaye', false),
  ('team', 'SEN', 'Senegal', 19, 'SEN19', 'Nicolas Jackson', false),
  ('team', 'SEN', 'Senegal', 20, 'SEN20', 'Krepin Diatta', false),
  ('team', 'IRQ', 'Irak', 1, 'IRQ1', 'Emblem', false),
  ('team', 'IRQ', 'Irak', 2, 'IRQ2', 'Jalal Hassan', false),
  ('team', 'IRQ', 'Irak', 3, 'IRQ3', 'Rebin Sulaka', false),
  ('team', 'IRQ', 'Irak', 4, 'IRQ4', 'Hussein Ali', false),
  ('team', 'IRQ', 'Irak', 5, 'IRQ5', 'Akam Hashem', false),
  ('team', 'IRQ', 'Irak', 6, 'IRQ6', 'Merchas Doski', false),
  ('team', 'IRQ', 'Irak', 7, 'IRQ7', 'Zaid Tahseen', false),
  ('team', 'IRQ', 'Irak', 8, 'IRQ8', 'Manaf Younis', false),
  ('team', 'IRQ', 'Irak', 9, 'IRQ9', 'Zidane Iqbal', false),
  ('team', 'IRQ', 'Irak', 10, 'IRQ10', 'Amir Al-Ammari', false),
  ('team', 'IRQ', 'Irak', 11, 'IRQ11', 'Ibrahim Bavesh', false),
  ('team', 'IRQ', 'Irak', 12, 'IRQ12', 'Ali Jasim', false),
  ('team', 'IRQ', 'Irak', 13, 'IRQ13', 'Team Photo', false),
  ('team', 'IRQ', 'Irak', 14, 'IRQ14', 'Youssef Amyn', false),
  ('team', 'IRQ', 'Irak', 15, 'IRQ15', 'Aimar Sher', false),
  ('team', 'IRQ', 'Irak', 16, 'IRQ16', 'Marko Farji', false),
  ('team', 'IRQ', 'Irak', 17, 'IRQ17', 'Osama Rashid', false),
  ('team', 'IRQ', 'Irak', 18, 'IRQ18', 'Ali Al-Hamadi', false),
  ('team', 'IRQ', 'Irak', 19, 'IRQ19', 'Aymen Hussein', false),
  ('team', 'IRQ', 'Irak', 20, 'IRQ20', 'Mohanad Ali', false),
  ('team', 'NOR', 'Noorwegen', 1, 'NOR1', 'Emblem', false),
  ('team', 'NOR', 'Noorwegen', 2, 'NOR2', 'Orjan Nyland', false),
  ('team', 'NOR', 'Noorwegen', 3, 'NOR3', 'Julian Ryerson', false),
  ('team', 'NOR', 'Noorwegen', 4, 'NOR4', 'Leo Ostigård', false),
  ('team', 'NOR', 'Noorwegen', 5, 'NOR5', 'Kristoffer Vassbakk Ajer', false),
  ('team', 'NOR', 'Noorwegen', 6, 'NOR6', 'Marcus Holmgren Pedersen', false),
  ('team', 'NOR', 'Noorwegen', 7, 'NOR7', 'David Møller Wolfe', false),
  ('team', 'NOR', 'Noorwegen', 8, 'NOR8', 'Torbjørn Heggem', false),
  ('team', 'NOR', 'Noorwegen', 9, 'NOR9', 'Morten Thorsby', false),
  ('team', 'NOR', 'Noorwegen', 10, 'NOR10', 'Martin Ødegaard', false),
  ('team', 'NOR', 'Noorwegen', 11, 'NOR11', 'Sander Berge', false),
  ('team', 'NOR', 'Noorwegen', 12, 'NOR12', 'Andreas Schjelderup', false),
  ('team', 'NOR', 'Noorwegen', 13, 'NOR13', 'Team Photo', false),
  ('team', 'NOR', 'Noorwegen', 14, 'NOR14', 'Patrick Berg', false),
  ('team', 'NOR', 'Noorwegen', 15, 'NOR15', 'Erling Haaland', false),
  ('team', 'NOR', 'Noorwegen', 16, 'NOR16', 'Alexander Sørloth', false),
  ('team', 'NOR', 'Noorwegen', 17, 'NOR17', 'Aron Dønnum', false),
  ('team', 'NOR', 'Noorwegen', 18, 'NOR18', 'Jorgen Strand Larsen', false),
  ('team', 'NOR', 'Noorwegen', 19, 'NOR19', 'Antonio Nusa', false),
  ('team', 'NOR', 'Noorwegen', 20, 'NOR20', 'Oscar Bobb', false),
  ('team', 'ARG', 'Argentinië', 1, 'ARG1', 'Emblem', false),
  ('team', 'ARG', 'Argentinië', 2, 'ARG2', 'Emiliano Martinez', false),
  ('team', 'ARG', 'Argentinië', 3, 'ARG3', 'Nahuel Molina', false),
  ('team', 'ARG', 'Argentinië', 4, 'ARG4', 'Cristian Romero', false),
  ('team', 'ARG', 'Argentinië', 5, 'ARG5', 'Nicolas Otamendi', false),
  ('team', 'ARG', 'Argentinië', 6, 'ARG6', 'Nicolas Tagliafico', false),
  ('team', 'ARG', 'Argentinië', 7, 'ARG7', 'Leonardo Balerdi', false),
  ('team', 'ARG', 'Argentinië', 8, 'ARG8', 'Enzo Fernandez', false),
  ('team', 'ARG', 'Argentinië', 9, 'ARG9', 'Alexis Mac Allister', false),
  ('team', 'ARG', 'Argentinië', 10, 'ARG10', 'Rodrigo De Paul', false),
  ('team', 'ARG', 'Argentinië', 11, 'ARG11', 'Exequiel Palacios', false),
  ('team', 'ARG', 'Argentinië', 12, 'ARG12', 'Leandro Paredes', false),
  ('team', 'ARG', 'Argentinië', 13, 'ARG13', 'Team Photo', false),
  ('team', 'ARG', 'Argentinië', 14, 'ARG14', 'Nico Paz', false),
  ('team', 'ARG', 'Argentinië', 15, 'ARG15', 'Franco Mastantuono', false),
  ('team', 'ARG', 'Argentinië', 16, 'ARG16', 'Nico Gonzalez', false),
  ('team', 'ARG', 'Argentinië', 17, 'ARG17', 'Lionel Messi', false),
  ('team', 'ARG', 'Argentinië', 18, 'ARG18', 'Lautaro Martinez', false),
  ('team', 'ARG', 'Argentinië', 19, 'ARG19', 'Julian Alvarez', false),
  ('team', 'ARG', 'Argentinië', 20, 'ARG20', 'Giuliano Simeone', false),
  ('team', 'ALG', 'Algerije', 1, 'ALG1', 'Emblem', false),
  ('team', 'ALG', 'Algerije', 2, 'ALG2', 'Alexis Guendouz', false),
  ('team', 'ALG', 'Algerije', 3, 'ALG3', 'Ramy Bensebaini', false),
  ('team', 'ALG', 'Algerije', 4, 'ALG4', 'Youcef Atal', false),
  ('team', 'ALG', 'Algerije', 5, 'ALG5', 'Rayan Aït-Nouri', false),
  ('team', 'ALG', 'Algerije', 6, 'ALG6', 'Mohamed Amine Tougai', false),
  ('team', 'ALG', 'Algerije', 7, 'ALG7', 'Aïssa Mandi', false),
  ('team', 'ALG', 'Algerije', 8, 'ALG8', 'Ismael Bennacer', false),
  ('team', 'ALG', 'Algerije', 9, 'ALG9', 'Houssem Aouar', false),
  ('team', 'ALG', 'Algerije', 10, 'ALG10', 'Hicham Boudaoui', false),
  ('team', 'ALG', 'Algerije', 11, 'ALG11', 'Ramiz Zerrouki', false),
  ('team', 'ALG', 'Algerije', 12, 'ALG12', 'Nabil Bentaleb', false),
  ('team', 'ALG', 'Algerije', 13, 'ALG13', 'Team Photo', false),
  ('team', 'ALG', 'Algerije', 14, 'ALG14', 'Farés Chaibi', false),
  ('team', 'ALG', 'Algerije', 15, 'ALG15', 'Riyad Mahrez', false),
  ('team', 'ALG', 'Algerije', 16, 'ALG16', 'Said Benrahma', false),
  ('team', 'ALG', 'Algerije', 17, 'ALG17', 'Anis Hadj Moussa', false),
  ('team', 'ALG', 'Algerije', 18, 'ALG18', 'Amine Gouiri', false),
  ('team', 'ALG', 'Algerije', 19, 'ALG19', 'Baghdad Bounedjah', false),
  ('team', 'ALG', 'Algerije', 20, 'ALG20', 'Mohammed Amoura', false),
  ('team', 'AUT', 'Oostenrijk', 1, 'AUT1', 'Emblem', false),
  ('team', 'AUT', 'Oostenrijk', 2, 'AUT2', 'Alexander Schlager', false),
  ('team', 'AUT', 'Oostenrijk', 3, 'AUT3', 'Patrick Pentz', false),
  ('team', 'AUT', 'Oostenrijk', 4, 'AUT4', 'David Alaba', false),
  ('team', 'AUT', 'Oostenrijk', 5, 'AUT5', 'Kevin Danso', false),
  ('team', 'AUT', 'Oostenrijk', 6, 'AUT6', 'Philipp Lienhart', false),
  ('team', 'AUT', 'Oostenrijk', 7, 'AUT7', 'Stefan Posch', false),
  ('team', 'AUT', 'Oostenrijk', 8, 'AUT8', 'Phillipp Mwene', false),
  ('team', 'AUT', 'Oostenrijk', 9, 'AUT9', 'Alexander Prass', false),
  ('team', 'AUT', 'Oostenrijk', 10, 'AUT10', 'Xaver Schlager', false),
  ('team', 'AUT', 'Oostenrijk', 11, 'AUT11', 'Marcel Sabitzer', false),
  ('team', 'AUT', 'Oostenrijk', 12, 'AUT12', 'Konrad Laimer', false),
  ('team', 'AUT', 'Oostenrijk', 13, 'AUT13', 'Team Photo', false),
  ('team', 'AUT', 'Oostenrijk', 14, 'AUT14', 'Florian Grillitsch', false),
  ('team', 'AUT', 'Oostenrijk', 15, 'AUT15', 'Nicolas Seiwald', false),
  ('team', 'AUT', 'Oostenrijk', 16, 'AUT16', 'Romano Schmid', false),
  ('team', 'AUT', 'Oostenrijk', 17, 'AUT17', 'Patrick Wimmer', false),
  ('team', 'AUT', 'Oostenrijk', 18, 'AUT18', 'Christoph Baumgartner', false),
  ('team', 'AUT', 'Oostenrijk', 19, 'AUT19', 'Michael Gregoritsch', false),
  ('team', 'AUT', 'Oostenrijk', 20, 'AUT20', 'Marko Arnautović', false),
  ('team', 'JOR', 'Jordanië', 1, 'JOR1', 'Emblem', false),
  ('team', 'JOR', 'Jordanië', 2, 'JOR2', 'Yazeed Abulaila', false),
  ('team', 'JOR', 'Jordanië', 3, 'JOR3', 'Ihsan Haddad', false),
  ('team', 'JOR', 'Jordanië', 4, 'JOR4', 'Mohammad Abu Hashish', false),
  ('team', 'JOR', 'Jordanië', 5, 'JOR5', 'Yazan Al-Arab', false),
  ('team', 'JOR', 'Jordanië', 6, 'JOR6', 'Abdallah Nasib', false),
  ('team', 'JOR', 'Jordanië', 7, 'JOR7', 'Saleem Obaid', false),
  ('team', 'JOR', 'Jordanië', 8, 'JOR8', 'Mohammad Abualnadi', false),
  ('team', 'JOR', 'Jordanië', 9, 'JOR9', 'Ibrahim Saadeh', false),
  ('team', 'JOR', 'Jordanië', 10, 'JOR10', 'Nizar Al-Rashdan', false),
  ('team', 'JOR', 'Jordanië', 11, 'JOR11', 'Noor Al-Rawabdeh', false),
  ('team', 'JOR', 'Jordanië', 12, 'JOR12', 'Mohannad Abu Taha', false),
  ('team', 'JOR', 'Jordanië', 13, 'JOR13', 'Team Photo', false),
  ('team', 'JOR', 'Jordanië', 14, 'JOR14', 'Amer Jamous', false),
  ('team', 'JOR', 'Jordanië', 15, 'JOR15', 'Musa Al-Taamari', false),
  ('team', 'JOR', 'Jordanië', 16, 'JOR16', 'Yazan Al-Naimat', false),
  ('team', 'JOR', 'Jordanië', 17, 'JOR17', 'Mahmoud Al-Mardi', false),
  ('team', 'JOR', 'Jordanië', 18, 'JOR18', 'Ali Olwan', false),
  ('team', 'JOR', 'Jordanië', 19, 'JOR19', 'Mohammad Abu Zrayq', false),
  ('team', 'JOR', 'Jordanië', 20, 'JOR20', 'Ibrahim Sabra', false),
  ('team', 'POR', 'Portugal', 1, 'POR1', 'Emblem', false),
  ('team', 'POR', 'Portugal', 2, 'POR2', 'Diogo Costa', false),
  ('team', 'POR', 'Portugal', 3, 'POR3', 'José Sá', false),
  ('team', 'POR', 'Portugal', 4, 'POR4', 'Ruben Dias', false),
  ('team', 'POR', 'Portugal', 5, 'POR5', 'João Cancelo', false),
  ('team', 'POR', 'Portugal', 6, 'POR6', 'Diogo Dalot', false),
  ('team', 'POR', 'Portugal', 7, 'POR7', 'Nuno Mendes', false),
  ('team', 'POR', 'Portugal', 8, 'POR8', 'Gonçalo Inácio', false),
  ('team', 'POR', 'Portugal', 9, 'POR9', 'Bernardo Silva', false),
  ('team', 'POR', 'Portugal', 10, 'POR10', 'Bruno Fernandes', false),
  ('team', 'POR', 'Portugal', 11, 'POR11', 'Ruben Neves', false),
  ('team', 'POR', 'Portugal', 12, 'POR12', 'Vitinha', false),
  ('team', 'POR', 'Portugal', 13, 'POR13', 'Team Photo', false),
  ('team', 'POR', 'Portugal', 14, 'POR14', 'João Neves', false),
  ('team', 'POR', 'Portugal', 15, 'POR15', 'Cristiano Ronaldo', false),
  ('team', 'POR', 'Portugal', 16, 'POR16', 'Francisco Trincao', false),
  ('team', 'POR', 'Portugal', 17, 'POR17', 'João Felix', false),
  ('team', 'POR', 'Portugal', 18, 'POR18', 'Gonçalo Ramos', false),
  ('team', 'POR', 'Portugal', 19, 'POR19', 'Pedro Neto', false),
  ('team', 'POR', 'Portugal', 20, 'POR20', 'Rafael Leão', false),
  ('team', 'COD', 'DR Congo', 1, 'COD1', 'Emblem', false),
  ('team', 'COD', 'DR Congo', 2, 'COD2', 'Lionel Mpasi-Nzau', false),
  ('team', 'COD', 'DR Congo', 3, 'COD3', 'Aaron Wan-Bissaka', false),
  ('team', 'COD', 'DR Congo', 4, 'COD4', 'Axel Tuanzebe', false),
  ('team', 'COD', 'DR Congo', 5, 'COD5', 'Arthur Masuaku', false),
  ('team', 'COD', 'DR Congo', 6, 'COD6', 'Chancel Mbemba', false),
  ('team', 'COD', 'DR Congo', 7, 'COD7', 'Joris Kayembe', false),
  ('team', 'COD', 'DR Congo', 8, 'COD8', 'Charles Pickel', false),
  ('team', 'COD', 'DR Congo', 9, 'COD9', 'Ngal''ayel Mukau', false),
  ('team', 'COD', 'DR Congo', 10, 'COD10', 'Edo Kayembe', false),
  ('team', 'COD', 'DR Congo', 11, 'COD11', 'Samuel Moutoussamy', false),
  ('team', 'COD', 'DR Congo', 12, 'COD12', 'Noah Sadiki', false),
  ('team', 'COD', 'DR Congo', 13, 'COD13', 'Team Photo', false),
  ('team', 'COD', 'DR Congo', 14, 'COD14', 'Théo Bongonda', false),
  ('team', 'COD', 'DR Congo', 15, 'COD15', 'Meschak Elia', false),
  ('team', 'COD', 'DR Congo', 16, 'COD16', 'Yoane Wissa', false),
  ('team', 'COD', 'DR Congo', 17, 'COD17', 'Brian Cipenga', false),
  ('team', 'COD', 'DR Congo', 18, 'COD18', 'Fiston Mayele', false),
  ('team', 'COD', 'DR Congo', 19, 'COD19', 'Cédric Bakambu', false),
  ('team', 'COD', 'DR Congo', 20, 'COD20', 'Nathanaël Mbuku', false),
  ('team', 'UZB', 'Oezbekistan', 1, 'UZB1', 'Emblem', false),
  ('team', 'UZB', 'Oezbekistan', 2, 'UZB2', 'Utkir Yusupov', false),
  ('team', 'UZB', 'Oezbekistan', 3, 'UZB3', 'Farrukh Savfiev', false),
  ('team', 'UZB', 'Oezbekistan', 4, 'UZB4', 'Sherzod Nasrullaev', false),
  ('team', 'UZB', 'Oezbekistan', 5, 'UZB5', 'Umar Eshmurodov', false),
  ('team', 'UZB', 'Oezbekistan', 6, 'UZB6', 'Husniddin Aliqulov', false),
  ('team', 'UZB', 'Oezbekistan', 7, 'UZB7', 'Rustamjon Ashurmatov', false),
  ('team', 'UZB', 'Oezbekistan', 8, 'UZB8', 'Khojiakbar Alijonov', false),
  ('team', 'UZB', 'Oezbekistan', 9, 'UZB9', 'Abdukodir Khusanov', false),
  ('team', 'UZB', 'Oezbekistan', 10, 'UZB10', 'Odiljon Hamrobekov', false),
  ('team', 'UZB', 'Oezbekistan', 11, 'UZB11', 'Otabek Shukurov', false),
  ('team', 'UZB', 'Oezbekistan', 12, 'UZB12', 'Jamshid Iskanderov', false),
  ('team', 'UZB', 'Oezbekistan', 13, 'UZB13', 'Team Photo', false),
  ('team', 'UZB', 'Oezbekistan', 14, 'UZB14', 'Azizbek Turgunboev', false),
  ('team', 'UZB', 'Oezbekistan', 15, 'UZB15', 'Khojimat Erkinov', false),
  ('team', 'UZB', 'Oezbekistan', 16, 'UZB16', 'Eldor Shomurodov', false),
  ('team', 'UZB', 'Oezbekistan', 17, 'UZB17', 'Oston Urunov', false),
  ('team', 'UZB', 'Oezbekistan', 18, 'UZB18', 'Jaloliddin Masharipov', false),
  ('team', 'UZB', 'Oezbekistan', 19, 'UZB19', 'Igor Sergeev', false),
  ('team', 'UZB', 'Oezbekistan', 20, 'UZB20', 'Abbosbek Fayzullaev', false),
  ('team', 'COL', 'Colombia', 1, 'COL1', 'Emblem', false),
  ('team', 'COL', 'Colombia', 2, 'COL2', 'Camilo Vargas', false),
  ('team', 'COL', 'Colombia', 3, 'COL3', 'David Ospina', false),
  ('team', 'COL', 'Colombia', 4, 'COL4', 'Dávinson Sánchez', false),
  ('team', 'COL', 'Colombia', 5, 'COL5', 'Yerry Mina', false),
  ('team', 'COL', 'Colombia', 6, 'COL6', 'Daniel Munoz', false),
  ('team', 'COL', 'Colombia', 7, 'COL7', 'Johan Mojica', false),
  ('team', 'COL', 'Colombia', 8, 'COL8', 'Jhon Lucumí', false),
  ('team', 'COL', 'Colombia', 9, 'COL9', 'Santiago Arias', false),
  ('team', 'COL', 'Colombia', 10, 'COL10', 'Jefferson Lerma', false),
  ('team', 'COL', 'Colombia', 11, 'COL11', 'Kevin Castaño', false),
  ('team', 'COL', 'Colombia', 12, 'COL12', 'Richard Rios', false),
  ('team', 'COL', 'Colombia', 13, 'COL13', 'Team Photo', false),
  ('team', 'COL', 'Colombia', 14, 'COL14', 'James Rodriguez', false),
  ('team', 'COL', 'Colombia', 15, 'COL15', 'Juan Fernando Quintero', false),
  ('team', 'COL', 'Colombia', 16, 'COL16', 'Jorge Carrascal', false),
  ('team', 'COL', 'Colombia', 17, 'COL17', 'Jhon Arias', false),
  ('team', 'COL', 'Colombia', 18, 'COL18', 'Jhon Cordova', false),
  ('team', 'COL', 'Colombia', 19, 'COL19', 'Luis Suarez', false),
  ('team', 'COL', 'Colombia', 20, 'COL20', 'Luis Diaz', false),
  ('team', 'ENG', 'Engeland', 1, 'ENG1', 'Emblem', false),
  ('team', 'ENG', 'Engeland', 2, 'ENG2', 'Jordan Pickford', false),
  ('team', 'ENG', 'Engeland', 3, 'ENG3', 'John Stones', false),
  ('team', 'ENG', 'Engeland', 4, 'ENG4', 'Marc Guéhi', false),
  ('team', 'ENG', 'Engeland', 5, 'ENG5', 'Ezri Konsa', false),
  ('team', 'ENG', 'Engeland', 6, 'ENG6', 'Trent Alexander-Arnold', false),
  ('team', 'ENG', 'Engeland', 7, 'ENG7', 'Reece James', false),
  ('team', 'ENG', 'Engeland', 8, 'ENG8', 'Dan Burn', false),
  ('team', 'ENG', 'Engeland', 9, 'ENG9', 'Jordan Henderson', false),
  ('team', 'ENG', 'Engeland', 10, 'ENG10', 'Declan Rice', false),
  ('team', 'ENG', 'Engeland', 11, 'ENG11', 'Jude Bellingham', false),
  ('team', 'ENG', 'Engeland', 12, 'ENG12', 'Cole Palmer', false),
  ('team', 'ENG', 'Engeland', 13, 'ENG13', 'Team Photo', false),
  ('team', 'ENG', 'Engeland', 14, 'ENG14', 'Morgan Rogers', false),
  ('team', 'ENG', 'Engeland', 15, 'ENG15', 'Anthony Gordon', false),
  ('team', 'ENG', 'Engeland', 16, 'ENG16', 'Phil Foden', false),
  ('team', 'ENG', 'Engeland', 17, 'ENG17', 'Bukayo Saka', false),
  ('team', 'ENG', 'Engeland', 18, 'ENG18', 'Harry Kane', false),
  ('team', 'ENG', 'Engeland', 19, 'ENG19', 'Marcus Rashford', false),
  ('team', 'ENG', 'Engeland', 20, 'ENG20', 'Ollie Watkins', false),
  ('team', 'CRO', 'Kroatië', 1, 'CRO1', 'Emblem', false),
  ('team', 'CRO', 'Kroatië', 2, 'CRO2', 'Dominik Livaković', false),
  ('team', 'CRO', 'Kroatië', 3, 'CRO3', 'Duje Caleta-Car', false),
  ('team', 'CRO', 'Kroatië', 4, 'CRO4', 'Josko Gvardiol', false),
  ('team', 'CRO', 'Kroatië', 5, 'CRO5', 'Josip Stanišić', false),
  ('team', 'CRO', 'Kroatië', 6, 'CRO6', 'Luka Vušković', false),
  ('team', 'CRO', 'Kroatië', 7, 'CRO7', 'Josip Sutalo', false),
  ('team', 'CRO', 'Kroatië', 8, 'CRO8', 'Kristijan Jakic', false),
  ('team', 'CRO', 'Kroatië', 9, 'CRO9', 'Luka Modrić', false),
  ('team', 'CRO', 'Kroatië', 10, 'CRO10', 'Mateo Kovacic', false),
  ('team', 'CRO', 'Kroatië', 11, 'CRO11', 'Martin Baturina', false),
  ('team', 'CRO', 'Kroatië', 12, 'CRO12', 'Lovro Majer', false),
  ('team', 'CRO', 'Kroatië', 13, 'CRO13', 'Team Photo', false),
  ('team', 'CRO', 'Kroatië', 14, 'CRO14', 'Mario Pasalic', false),
  ('team', 'CRO', 'Kroatië', 15, 'CRO15', 'Petar Sucic', false),
  ('team', 'CRO', 'Kroatië', 16, 'CRO16', 'Ivan Perišić', false),
  ('team', 'CRO', 'Kroatië', 17, 'CRO17', 'Marco Pasalic', false),
  ('team', 'CRO', 'Kroatië', 18, 'CRO18', 'Ante Budimir', false),
  ('team', 'CRO', 'Kroatië', 19, 'CRO19', 'Andrej Kramarić', false),
  ('team', 'CRO', 'Kroatië', 20, 'CRO20', 'Franjo Ivanovic', false),
  ('team', 'GHA', 'Ghana', 1, 'GHA1', 'Emblem', false),
  ('team', 'GHA', 'Ghana', 2, 'GHA2', 'Lawrence Ati Zigi', false),
  ('team', 'GHA', 'Ghana', 3, 'GHA3', 'Tariq Lamptey', false),
  ('team', 'GHA', 'Ghana', 4, 'GHA4', 'Mohammed Salisu', false),
  ('team', 'GHA', 'Ghana', 5, 'GHA5', 'Alidu Seidu', false),
  ('team', 'GHA', 'Ghana', 6, 'GHA6', 'Alexander Djiku', false),
  ('team', 'GHA', 'Ghana', 7, 'GHA7', 'Gideon Mensah', false),
  ('team', 'GHA', 'Ghana', 8, 'GHA8', 'Caleb Yirenkyi', false),
  ('team', 'GHA', 'Ghana', 9, 'GHA9', 'Abdul Issahaku Fatawu', false),
  ('team', 'GHA', 'Ghana', 10, 'GHA10', 'Thomas Partey', false),
  ('team', 'GHA', 'Ghana', 11, 'GHA11', 'Salis Abdul Samed', false),
  ('team', 'GHA', 'Ghana', 12, 'GHA12', 'Kamaldeen Sulemana', false),
  ('team', 'GHA', 'Ghana', 13, 'GHA13', 'Team Photo', false),
  ('team', 'GHA', 'Ghana', 14, 'GHA14', 'Mohammed Kudus', false),
  ('team', 'GHA', 'Ghana', 15, 'GHA15', 'Inaki Williams', false),
  ('team', 'GHA', 'Ghana', 16, 'GHA16', 'Jordan Ayew', false),
  ('team', 'GHA', 'Ghana', 17, 'GHA17', 'André Ayew', false),
  ('team', 'GHA', 'Ghana', 18, 'GHA18', 'Joseph Paintsil', false),
  ('team', 'GHA', 'Ghana', 19, 'GHA19', 'Osman Bukari', false),
  ('team', 'GHA', 'Ghana', 20, 'GHA20', 'Antoine Semenyo', false),
  ('team', 'PAN', 'Panama', 1, 'PAN1', 'Emblem', false),
  ('team', 'PAN', 'Panama', 2, 'PAN2', 'Orlando Mosquera', false),
  ('team', 'PAN', 'Panama', 3, 'PAN3', 'Luis Mejia', false),
  ('team', 'PAN', 'Panama', 4, 'PAN4', 'Fidel Escobar', false),
  ('team', 'PAN', 'Panama', 5, 'PAN5', 'Andres Andrade', false),
  ('team', 'PAN', 'Panama', 6, 'PAN6', 'Michael Amir Murillo', false),
  ('team', 'PAN', 'Panama', 7, 'PAN7', 'Eric Davis', false),
  ('team', 'PAN', 'Panama', 8, 'PAN8', 'Jose Cordoba', false),
  ('team', 'PAN', 'Panama', 9, 'PAN9', 'Cesar Blackman', false),
  ('team', 'PAN', 'Panama', 10, 'PAN10', 'Cristian Martinez', false),
  ('team', 'PAN', 'Panama', 11, 'PAN11', 'Aníbal Godoy', false),
  ('team', 'PAN', 'Panama', 12, 'PAN12', 'Adalberto Carrasquilla', false),
  ('team', 'PAN', 'Panama', 13, 'PAN13', 'Team Photo', false),
  ('team', 'PAN', 'Panama', 14, 'PAN14', 'Édgar Bárcenas', false),
  ('team', 'PAN', 'Panama', 15, 'PAN15', 'Carlos Harvey', false),
  ('team', 'PAN', 'Panama', 16, 'PAN16', 'Ismael Díaz', false),
  ('team', 'PAN', 'Panama', 17, 'PAN17', 'Jose Fajardo', false),
  ('team', 'PAN', 'Panama', 18, 'PAN18', 'Cecilio Waterman', false),
  ('team', 'PAN', 'Panama', 19, 'PAN19', 'Jose Luiz Rodriguez', false),
  ('team', 'PAN', 'Panama', 20, 'PAN20', 'Alberto Quintero', false),
  ('special', 'FWC', 'WK-specials', 9, 'FWC9', 'Italy 1934', false),
  ('special', 'FWC', 'WK-specials', 10, 'FWC10', 'Uruguay 1950', false),
  ('special', 'FWC', 'WK-specials', 11, 'FWC11', 'West Germany 1954', false),
  ('special', 'FWC', 'WK-specials', 12, 'FWC12', 'Brazil 1962', false),
  ('special', 'FWC', 'WK-specials', 13, 'FWC13', 'West Germany 1974', false),
  ('special', 'FWC', 'WK-specials', 14, 'FWC14', 'Argentina 1986', false),
  ('special', 'FWC', 'WK-specials', 15, 'FWC15', 'Brazil 1994', false),
  ('special', 'FWC', 'WK-specials', 16, 'FWC16', 'Brazil 2002', false),
  ('special', 'FWC', 'WK-specials', 17, 'FWC17', 'Italy 2006', false),
  ('special', 'FWC', 'WK-specials', 18, 'FWC18', 'Germany 2014', false),
  ('special', 'FWC', 'WK-specials', 19, 'FWC19', 'Argentina 2022', false)
on conflict (code) do nothing;
